package com.etong.pt.data.response;

import java.util.ArrayList;
import java.util.List;

public class UserResponseExample{
    protected String limitClause;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    public UserResponseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public String getLimitClause() {
        return limitClause;
    }

    public void setLimitClause(Integer start,Integer limit) {
        if (start==null || limit==null){
            return;
        }
        if (start< 0){
            start=0;
        }
        limitClause=String.format("limit %d, %d", start, limit);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andF_rpidIsNull() {
            addCriterion("f_rpid is null");
            return (Criteria) this;
        }

        public Criteria andF_rpidIsNotNull() {
            addCriterion("f_rpid is not null");
            return (Criteria) this;
        }

        public Criteria andF_rpidEqualTo(Long value) {
            addCriterion("f_rpid =", value, "f_rpid");
            return (Criteria) this;
        }

        public Criteria andF_rpidNotEqualTo(Long value) {
            addCriterion("f_rpid <>", value, "f_rpid");
            return (Criteria) this;
        }

        public Criteria andF_rpidGreaterThan(Long value) {
            addCriterion("f_rpid >", value, "f_rpid");
            return (Criteria) this;
        }

        public Criteria andF_rpidGreaterThanOrEqualTo(Long value) {
            addCriterion("f_rpid >=", value, "f_rpid");
            return (Criteria) this;
        }

        public Criteria andF_rpidLessThan(Long value) {
            addCriterion("f_rpid <", value, "f_rpid");
            return (Criteria) this;
        }

        public Criteria andF_rpidLessThanOrEqualTo(Long value) {
            addCriterion("f_rpid <=", value, "f_rpid");
            return (Criteria) this;
        }

        public Criteria andF_rpidIn(List<Long> values) {
            addCriterion("f_rpid in", values, "f_rpid");
            return (Criteria) this;
        }

        public Criteria andF_rpidNotIn(List<Long> values) {
            addCriterion("f_rpid not in", values, "f_rpid");
            return (Criteria) this;
        }

        public Criteria andF_rpidBetween(Long value1, Long value2) {
            addCriterion("f_rpid between", value1, value2, "f_rpid");
            return (Criteria) this;
        }

        public Criteria andF_rpidNotBetween(Long value1, Long value2) {
            addCriterion("f_rpid not between", value1, value2, "f_rpid");
            return (Criteria) this;
        }

        public Criteria andF_contentIsNull() {
            addCriterion("f_content is null");
            return (Criteria) this;
        }

        public Criteria andF_contentIsNotNull() {
            addCriterion("f_content is not null");
            return (Criteria) this;
        }

        public Criteria andF_contentEqualTo(String value) {
            addCriterion("f_content =", value, "f_content");
            return (Criteria) this;
        }

        public Criteria andF_contentNotEqualTo(String value) {
            addCriterion("f_content <>", value, "f_content");
            return (Criteria) this;
        }

        public Criteria andF_contentGreaterThan(String value) {
            addCriterion("f_content >", value, "f_content");
            return (Criteria) this;
        }

        public Criteria andF_contentGreaterThanOrEqualTo(String value) {
            addCriterion("f_content >=", value, "f_content");
            return (Criteria) this;
        }

        public Criteria andF_contentLessThan(String value) {
            addCriterion("f_content <", value, "f_content");
            return (Criteria) this;
        }

        public Criteria andF_contentLessThanOrEqualTo(String value) {
            addCriterion("f_content <=", value, "f_content");
            return (Criteria) this;
        }

        public Criteria andF_contentLike(String value) {
            addCriterion("f_content like", value, "f_content");
            return (Criteria) this;
        }

        public Criteria andF_contentNotLike(String value) {
            addCriterion("f_content not like", value, "f_content");
            return (Criteria) this;
        }

        public Criteria andF_contentIn(List<String> values) {
            addCriterion("f_content in", values, "f_content");
            return (Criteria) this;
        }

        public Criteria andF_contentNotIn(List<String> values) {
            addCriterion("f_content not in", values, "f_content");
            return (Criteria) this;
        }

        public Criteria andF_contentBetween(String value1, String value2) {
            addCriterion("f_content between", value1, value2, "f_content");
            return (Criteria) this;
        }

        public Criteria andF_contentNotBetween(String value1, String value2) {
            addCriterion("f_content not between", value1, value2, "f_content");
            return (Criteria) this;
        }

        public Criteria andF_createtimeIsNull() {
            addCriterion("f_createtime is null");
            return (Criteria) this;
        }

        public Criteria andF_createtimeIsNotNull() {
            addCriterion("f_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andF_createtimeEqualTo(Integer value) {
            addCriterion("f_createtime =", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeNotEqualTo(Integer value) {
            addCriterion("f_createtime <>", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeGreaterThan(Integer value) {
            addCriterion("f_createtime >", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_createtime >=", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeLessThan(Integer value) {
            addCriterion("f_createtime <", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeLessThanOrEqualTo(Integer value) {
            addCriterion("f_createtime <=", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeIn(List<Integer> values) {
            addCriterion("f_createtime in", values, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeNotIn(List<Integer> values) {
            addCriterion("f_createtime not in", values, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeBetween(Integer value1, Integer value2) {
            addCriterion("f_createtime between", value1, value2, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("f_createtime not between", value1, value2, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_readIsNull() {
            addCriterion("f_read is null");
            return (Criteria) this;
        }

        public Criteria andF_readIsNotNull() {
            addCriterion("f_read is not null");
            return (Criteria) this;
        }

        public Criteria andF_readEqualTo(Boolean value) {
            addCriterion("f_read =", value, "f_read");
            return (Criteria) this;
        }

        public Criteria andF_readNotEqualTo(Boolean value) {
            addCriterion("f_read <>", value, "f_read");
            return (Criteria) this;
        }

        public Criteria andF_readGreaterThan(Boolean value) {
            addCriterion("f_read >", value, "f_read");
            return (Criteria) this;
        }

        public Criteria andF_readGreaterThanOrEqualTo(Boolean value) {
            addCriterion("f_read >=", value, "f_read");
            return (Criteria) this;
        }

        public Criteria andF_readLessThan(Boolean value) {
            addCriterion("f_read <", value, "f_read");
            return (Criteria) this;
        }

        public Criteria andF_readLessThanOrEqualTo(Boolean value) {
            addCriterion("f_read <=", value, "f_read");
            return (Criteria) this;
        }

        public Criteria andF_readIn(List<Boolean> values) {
            addCriterion("f_read in", values, "f_read");
            return (Criteria) this;
        }

        public Criteria andF_readNotIn(List<Boolean> values) {
            addCriterion("f_read not in", values, "f_read");
            return (Criteria) this;
        }

        public Criteria andF_readBetween(Boolean value1, Boolean value2) {
            addCriterion("f_read between", value1, value2, "f_read");
            return (Criteria) this;
        }

        public Criteria andF_readNotBetween(Boolean value1, Boolean value2) {
            addCriterion("f_read not between", value1, value2, "f_read");
            return (Criteria) this;
        }

        public Criteria andF_nameIsNull() {
            addCriterion("f_name is null");
            return (Criteria) this;
        }

        public Criteria andF_nameIsNotNull() {
            addCriterion("f_name is not null");
            return (Criteria) this;
        }

        public Criteria andF_nameEqualTo(String value) {
            addCriterion("f_name =", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotEqualTo(String value) {
            addCriterion("f_name <>", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameGreaterThan(String value) {
            addCriterion("f_name >", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameGreaterThanOrEqualTo(String value) {
            addCriterion("f_name >=", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameLessThan(String value) {
            addCriterion("f_name <", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameLessThanOrEqualTo(String value) {
            addCriterion("f_name <=", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameLike(String value) {
            addCriterion("f_name like", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotLike(String value) {
            addCriterion("f_name not like", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameIn(List<String> values) {
            addCriterion("f_name in", values, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotIn(List<String> values) {
            addCriterion("f_name not in", values, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameBetween(String value1, String value2) {
            addCriterion("f_name between", value1, value2, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotBetween(String value1, String value2) {
            addCriterion("f_name not between", value1, value2, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_phoneIsNull() {
            addCriterion("f_phone is null");
            return (Criteria) this;
        }

        public Criteria andF_phoneIsNotNull() {
            addCriterion("f_phone is not null");
            return (Criteria) this;
        }

        public Criteria andF_phoneEqualTo(String value) {
            addCriterion("f_phone =", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotEqualTo(String value) {
            addCriterion("f_phone <>", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneGreaterThan(String value) {
            addCriterion("f_phone >", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneGreaterThanOrEqualTo(String value) {
            addCriterion("f_phone >=", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLessThan(String value) {
            addCriterion("f_phone <", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLessThanOrEqualTo(String value) {
            addCriterion("f_phone <=", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLike(String value) {
            addCriterion("f_phone like", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotLike(String value) {
            addCriterion("f_phone not like", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneIn(List<String> values) {
            addCriterion("f_phone in", values, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotIn(List<String> values) {
            addCriterion("f_phone not in", values, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneBetween(String value1, String value2) {
            addCriterion("f_phone between", value1, value2, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotBetween(String value1, String value2) {
            addCriterion("f_phone not between", value1, value2, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_midIsNull() {
            addCriterion("f_mid is null");
            return (Criteria) this;
        }

        public Criteria andF_midIsNotNull() {
            addCriterion("f_mid is not null");
            return (Criteria) this;
        }

        public Criteria andF_midEqualTo(Long value) {
            addCriterion("f_mid =", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotEqualTo(Long value) {
            addCriterion("f_mid <>", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midGreaterThan(Long value) {
            addCriterion("f_mid >", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midGreaterThanOrEqualTo(Long value) {
            addCriterion("f_mid >=", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midLessThan(Long value) {
            addCriterion("f_mid <", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midLessThanOrEqualTo(Long value) {
            addCriterion("f_mid <=", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midIn(List<Long> values) {
            addCriterion("f_mid in", values, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotIn(List<Long> values) {
            addCriterion("f_mid not in", values, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midBetween(Long value1, Long value2) {
            addCriterion("f_mid between", value1, value2, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotBetween(Long value1, Long value2) {
            addCriterion("f_mid not between", value1, value2, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_stidIsNull() {
            addCriterion("f_stid is null");
            return (Criteria) this;
        }

        public Criteria andF_stidIsNotNull() {
            addCriterion("f_stid is not null");
            return (Criteria) this;
        }

        public Criteria andF_stidEqualTo(String value) {
            addCriterion("f_stid =", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidNotEqualTo(String value) {
            addCriterion("f_stid <>", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidGreaterThan(String value) {
            addCriterion("f_stid >", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidGreaterThanOrEqualTo(String value) {
            addCriterion("f_stid >=", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidLessThan(String value) {
            addCriterion("f_stid <", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidLessThanOrEqualTo(String value) {
            addCriterion("f_stid <=", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidLike(String value) {
            addCriterion("f_stid like", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidNotLike(String value) {
            addCriterion("f_stid not like", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidIn(List<String> values) {
            addCriterion("f_stid in", values, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidNotIn(List<String> values) {
            addCriterion("f_stid not in", values, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidBetween(String value1, String value2) {
            addCriterion("f_stid between", value1, value2, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidNotBetween(String value1, String value2) {
            addCriterion("f_stid not between", value1, value2, "f_stid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bd_response
     *
     * @mbggenerated do_not_delete_during_merge Tue Jan 05 15:52:28 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bd_response
     *
     * @mbggenerated Tue Jan 05 15:52:28 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}