package com.etong.pt.data.collection;

import java.io.Serializable;

public class CollectionVehicle implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_collectionvehicle.f_clid
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    private Long f_clid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_collectionvehicle.f_vid
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    private Integer f_vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_collectionvehicle.f_collecttime
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    private Integer f_collecttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_collectionvehicle.f_mid
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    private Long f_mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_collectionvehicle.f_stid
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    private String f_stid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_collectionvehicle.f_clid
     *
     * @return the value of t_bd_collectionvehicle.f_clid
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    public Long getF_clid() {
        return f_clid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_collectionvehicle.f_clid
     *
     * @param f_clid the value for t_bd_collectionvehicle.f_clid
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    public void setF_clid(Long f_clid) {
        this.f_clid = f_clid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_collectionvehicle.f_vid
     *
     * @return the value of t_bd_collectionvehicle.f_vid
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    public Integer getF_vid() {
        return f_vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_collectionvehicle.f_vid
     *
     * @param f_vid the value for t_bd_collectionvehicle.f_vid
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    public void setF_vid(Integer f_vid) {
        this.f_vid = f_vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_collectionvehicle.f_collecttime
     *
     * @return the value of t_bd_collectionvehicle.f_collecttime
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    public Integer getF_collecttime() {
        return f_collecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_collectionvehicle.f_collecttime
     *
     * @param f_collecttime the value for t_bd_collectionvehicle.f_collecttime
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    public void setF_collecttime(Integer f_collecttime) {
        this.f_collecttime = f_collecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_collectionvehicle.f_mid
     *
     * @return the value of t_bd_collectionvehicle.f_mid
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    public Long getF_mid() {
        return f_mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_collectionvehicle.f_mid
     *
     * @param f_mid the value for t_bd_collectionvehicle.f_mid
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    public void setF_mid(Long f_mid) {
        this.f_mid = f_mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_collectionvehicle.f_stid
     *
     * @return the value of t_bd_collectionvehicle.f_stid
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    public String getF_stid() {
        return f_stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_collectionvehicle.f_stid
     *
     * @param f_stid the value for t_bd_collectionvehicle.f_stid
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    public void setF_stid(String f_stid) {
        this.f_stid = f_stid == null ? null : f_stid.trim();
    }
}