package com.etong.pt.data.collection;

import com.etong.pt.data.collection.CollectionVehicle;
import com.etong.pt.data.collection.CollectionVehicleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectionVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_collectionvehicle
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    int countByExample(CollectionVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_collectionvehicle
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    int deleteByExample(CollectionVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_collectionvehicle
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    int deleteByPrimaryKey(Long f_clid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_collectionvehicle
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    int insert(CollectionVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_collectionvehicle
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    int insertSelective(CollectionVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_collectionvehicle
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    List<CollectionVehicle> selectByExample(CollectionVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_collectionvehicle
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    CollectionVehicle selectByPrimaryKey(Long f_clid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_collectionvehicle
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") CollectionVehicle record, @Param("example") CollectionVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_collectionvehicle
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    int updateByExample(@Param("record") CollectionVehicle record, @Param("example") CollectionVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_collectionvehicle
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    int updateByPrimaryKeySelective(CollectionVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_collectionvehicle
     *
     * @mbggenerated Wed Oct 28 14:04:38 CST 2015
     */
    int updateByPrimaryKey(CollectionVehicle record);
}