package com.etong.pt.data.order;


import java.io.Serializable;

public class Order implements Serializable {

    private Integer f_remiantime;//作废剩余时间

    private Integer baiduRemainTime;

    private Integer blogRemainTime;

    private Integer wechatRemainTime;

    private Long f_acid;//活动ID，用户统计活动产生订单情况，增加日期：2015-12-3

    private String f_editordesc;//编辑者备注，增加日期：2015-12-18
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_ofid
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Long f_ofid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_ofcode
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_ofcode;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_mid
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Long f_mid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_name
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_name;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_phone
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_phone;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_carbrand
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_carbrand;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_carset
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_carset;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_cartype
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_cartype;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_carbrandid
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Integer f_carbrandid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_carsetid
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Integer f_carsetid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_cartypeid
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Integer f_cartypeid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_dvid
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Long f_dvid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_operatorid
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Long f_operatorid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_operator
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_operator;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_operatetime
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Integer f_operatetime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_createtime
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Integer f_createtime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_status
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Integer f_status;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_bottomprice
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Double f_bottomprice;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_payments
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Double f_payments;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_paymode
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Integer f_paymode;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_payitem
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Integer f_payitem;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_paycode
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_paycode;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_paytime
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Integer f_paytime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_ncid
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Integer f_ncid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_purchaseway
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Integer f_purchaseway;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_expecttime
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_expecttime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_ncname
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_ncname;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_saleman
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_saleman;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_salephone
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_salephone;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_color
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_color;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_type
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Integer f_type;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_dcid
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Long f_dcid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_valid
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Boolean f_valid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_wechatshare
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Boolean f_wechatshare;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_blogshare
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Boolean f_blogshare;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_baidushare
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Boolean f_baidushare;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_derate
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private Double f_derate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_stid
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_stid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_licenceaddress
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_licenceaddress;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_orderform.f_desc
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    private String f_desc;
    private Integer f_wechattime;
    private Integer f_blogtime;
    private Integer f_baidutime;

    public String getF_editordesc() {
        return f_editordesc;
    }

    public void setF_editordesc(String f_editordesc) {
        this.f_editordesc = f_editordesc;
    }

    public Long getF_acid() {
        return f_acid;
    }

    public void setF_acid(Long f_acid) {
        this.f_acid = f_acid;
    }

    public Integer getBaiduRemainTime() {
        return baiduRemainTime;
    }

    public void setBaiduRemainTime(Integer baiduRemainTime) {
        this.baiduRemainTime = baiduRemainTime;
    }

    public Integer getBlogRemainTime() {
        return blogRemainTime;
    }

    public void setBlogRemainTime(Integer blogRemainTime) {
        this.blogRemainTime = blogRemainTime;
    }

    public Integer getWechatRemainTime() {
        return wechatRemainTime;
    }

    public void setWechatRemainTime(Integer wechatRemainTime) {
        this.wechatRemainTime = wechatRemainTime;
    }

    public Integer getF_wechattime() {
        return f_wechattime;
    }

    public void setF_wechattime(Integer f_wechattime) {
        this.f_wechattime = f_wechattime;
    }

    public Integer getF_blogtime() {
        return f_blogtime;
    }

    public void setF_blogtime(Integer f_blogtime) {
        this.f_blogtime = f_blogtime;
    }

    public Integer getF_baidutime() {
        return f_baidutime;
    }

    public void setF_baidutime(Integer f_baidutime) {
        this.f_baidutime = f_baidutime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_ofid
     *
     * @return the value of t_bd_orderform.f_ofid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */

    public Long getF_ofid() {
        return f_ofid;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_ofid
     *
     * @param f_ofid the value for t_bd_orderform.f_ofid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_ofid(Long f_ofid) {
        this.f_ofid = f_ofid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_ofcode
     *
     * @return the value of t_bd_orderform.f_ofcode
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_ofcode() {
        return f_ofcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_ofcode
     *
     * @param f_ofcode the value for t_bd_orderform.f_ofcode
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_ofcode(String f_ofcode) {
        this.f_ofcode = f_ofcode == null ? null : f_ofcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_mid
     *
     * @return the value of t_bd_orderform.f_mid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Long getF_mid() {
        return f_mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_mid
     *
     * @param f_mid the value for t_bd_orderform.f_mid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_mid(Long f_mid) {
        this.f_mid = f_mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_name
     *
     * @return the value of t_bd_orderform.f_name
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_name() {
        return f_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_name
     *
     * @param f_name the value for t_bd_orderform.f_name
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_name(String f_name) {
        this.f_name = f_name == null ? null : f_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_phone
     *
     * @return the value of t_bd_orderform.f_phone
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_phone() {
        return f_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_phone
     *
     * @param f_phone the value for t_bd_orderform.f_phone
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_phone(String f_phone) {
        this.f_phone = f_phone == null ? null : f_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_carbrand
     *
     * @return the value of t_bd_orderform.f_carbrand
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_carbrand() {
        return f_carbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_carbrand
     *
     * @param f_carbrand the value for t_bd_orderform.f_carbrand
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_carbrand(String f_carbrand) {
        this.f_carbrand = f_carbrand == null ? null : f_carbrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_carset
     *
     * @return the value of t_bd_orderform.f_carset
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_carset() {
        return f_carset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_carset
     *
     * @param f_carset the value for t_bd_orderform.f_carset
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_carset(String f_carset) {
        this.f_carset = f_carset == null ? null : f_carset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_cartype
     *
     * @return the value of t_bd_orderform.f_cartype
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_cartype() {
        return f_cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_cartype
     *
     * @param f_cartype the value for t_bd_orderform.f_cartype
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_cartype(String f_cartype) {
        this.f_cartype = f_cartype == null ? null : f_cartype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_carbrandid
     *
     * @return the value of t_bd_orderform.f_carbrandid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Integer getF_carbrandid() {
        return f_carbrandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_carbrandid
     *
     * @param f_carbrandid the value for t_bd_orderform.f_carbrandid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_carbrandid(Integer f_carbrandid) {
        this.f_carbrandid = f_carbrandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_carsetid
     *
     * @return the value of t_bd_orderform.f_carsetid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Integer getF_carsetid() {
        return f_carsetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_carsetid
     *
     * @param f_carsetid the value for t_bd_orderform.f_carsetid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_carsetid(Integer f_carsetid) {
        this.f_carsetid = f_carsetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_cartypeid
     *
     * @return the value of t_bd_orderform.f_cartypeid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Integer getF_cartypeid() {
        return f_cartypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_cartypeid
     *
     * @param f_cartypeid the value for t_bd_orderform.f_cartypeid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_cartypeid(Integer f_cartypeid) {
        this.f_cartypeid = f_cartypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_dvid
     *
     * @return the value of t_bd_orderform.f_dvid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Long getF_dvid() {
        return f_dvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_dvid
     *
     * @param f_dvid the value for t_bd_orderform.f_dvid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_dvid(Long f_dvid) {
        this.f_dvid = f_dvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_operatorid
     *
     * @return the value of t_bd_orderform.f_operatorid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Long getF_operatorid() {
        return f_operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_operatorid
     *
     * @param f_operatorid the value for t_bd_orderform.f_operatorid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_operatorid(Long f_operatorid) {
        this.f_operatorid = f_operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_operator
     *
     * @return the value of t_bd_orderform.f_operator
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_operator() {
        return f_operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_operator
     *
     * @param f_operator the value for t_bd_orderform.f_operator
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_operator(String f_operator) {
        this.f_operator = f_operator == null ? null : f_operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_operatetime
     *
     * @return the value of t_bd_orderform.f_operatetime
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Integer getF_operatetime() {
        return f_operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_operatetime
     *
     * @param f_operatetime the value for t_bd_orderform.f_operatetime
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_operatetime(Integer f_operatetime) {
        this.f_operatetime = f_operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_createtime
     *
     * @return the value of t_bd_orderform.f_createtime
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Integer getF_createtime() {
        return f_createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_createtime
     *
     * @param f_createtime the value for t_bd_orderform.f_createtime
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_createtime(Integer f_createtime) {
        this.f_createtime = f_createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_status
     *
     * @return the value of t_bd_orderform.f_status
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Integer getF_status() {
        return f_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_status
     *
     * @param f_status the value for t_bd_orderform.f_status
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_status(Integer f_status) {
        this.f_status = f_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_bottomprice
     *
     * @return the value of t_bd_orderform.f_bottomprice
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Double getF_bottomprice() {
        return f_bottomprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_bottomprice
     *
     * @param f_bottomprice the value for t_bd_orderform.f_bottomprice
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_bottomprice(Double f_bottomprice) {
        this.f_bottomprice = f_bottomprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_payments
     *
     * @return the value of t_bd_orderform.f_payments
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Double getF_payments() {
        return f_payments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_payments
     *
     * @param f_payments the value for t_bd_orderform.f_payments
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_payments(Double f_payments) {
        this.f_payments = f_payments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_paymode
     *
     * @return the value of t_bd_orderform.f_paymode
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Integer getF_paymode() {
        return f_paymode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_paymode
     *
     * @param f_paymode the value for t_bd_orderform.f_paymode
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_paymode(Integer f_paymode) {
        this.f_paymode = f_paymode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_payitem
     *
     * @return the value of t_bd_orderform.f_payitem
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Integer getF_payitem() {
        return f_payitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_payitem
     *
     * @param f_payitem the value for t_bd_orderform.f_payitem
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_payitem(Integer f_payitem) {
        this.f_payitem = f_payitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_paycode
     *
     * @return the value of t_bd_orderform.f_paycode
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_paycode() {
        return f_paycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_paycode
     *
     * @param f_paycode the value for t_bd_orderform.f_paycode
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_paycode(String f_paycode) {
        this.f_paycode = f_paycode == null ? null : f_paycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_paytime
     *
     * @return the value of t_bd_orderform.f_paytime
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Integer getF_paytime() {
        return f_paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_paytime
     *
     * @param f_paytime the value for t_bd_orderform.f_paytime
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_paytime(Integer f_paytime) {
        this.f_paytime = f_paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_ncid
     *
     * @return the value of t_bd_orderform.f_ncid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Integer getF_ncid() {
        return f_ncid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_ncid
     *
     * @param f_ncid the value for t_bd_orderform.f_ncid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_ncid(Integer f_ncid) {
        this.f_ncid = f_ncid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_purchaseway
     *
     * @return the value of t_bd_orderform.f_purchaseway
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Integer getF_purchaseway() {
        return f_purchaseway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_purchaseway
     *
     * @param f_purchaseway the value for t_bd_orderform.f_purchaseway
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_purchaseway(Integer f_purchaseway) {
        this.f_purchaseway = f_purchaseway;
    }

    public Integer getF_remiantime() {
        return f_remiantime;
    }

    public void setF_remiantime(Integer f_remiantime) {
        this.f_remiantime = f_remiantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_expecttime
     *
     * @return the value of t_bd_orderform.f_expecttime
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_expecttime() {
        return f_expecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_expecttime
     *
     * @param f_expecttime the value for t_bd_orderform.f_expecttime
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_expecttime(String f_expecttime) {
        this.f_expecttime = f_expecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_ncname
     *
     * @return the value of t_bd_orderform.f_ncname
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_ncname() {
        return f_ncname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_ncname
     *
     * @param f_ncname the value for t_bd_orderform.f_ncname
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_ncname(String f_ncname) {
        this.f_ncname = f_ncname == null ? null : f_ncname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_saleman
     *
     * @return the value of t_bd_orderform.f_saleman
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_saleman() {
        return f_saleman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_saleman
     *
     * @param f_saleman the value for t_bd_orderform.f_saleman
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_saleman(String f_saleman) {
        this.f_saleman = f_saleman == null ? null : f_saleman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_salephone
     *
     * @return the value of t_bd_orderform.f_salephone
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_salephone() {
        return f_salephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_salephone
     *
     * @param f_salephone the value for t_bd_orderform.f_salephone
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_salephone(String f_salephone) {
        this.f_salephone = f_salephone == null ? null : f_salephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_color
     *
     * @return the value of t_bd_orderform.f_color
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_color() {
        return f_color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_color
     *
     * @param f_color the value for t_bd_orderform.f_color
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_color(String f_color) {
        this.f_color = f_color == null ? null : f_color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_type
     *
     * @return the value of t_bd_orderform.f_type
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Integer getF_type() {
        return f_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_type
     *
     * @param f_type the value for t_bd_orderform.f_type
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_type(Integer f_type) {
        this.f_type = f_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_dcid
     *
     * @return the value of t_bd_orderform.f_dcid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Long getF_dcid() {
        return f_dcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_dcid
     *
     * @param f_dcid the value for t_bd_orderform.f_dcid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_dcid(Long f_dcid) {
        this.f_dcid = f_dcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_valid
     *
     * @return the value of t_bd_orderform.f_valid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Boolean getF_valid() {
        return f_valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_valid
     *
     * @param f_valid the value for t_bd_orderform.f_valid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_valid(Boolean f_valid) {
        this.f_valid = f_valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_wechatshare
     *
     * @return the value of t_bd_orderform.f_wechatshare
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Boolean getF_wechatshare() {
        return f_wechatshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_wechatshare
     *
     * @param f_wechatshare the value for t_bd_orderform.f_wechatshare
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_wechatshare(Boolean f_wechatshare) {
        this.f_wechatshare = f_wechatshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_blogshare
     *
     * @return the value of t_bd_orderform.f_blogshare
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Boolean getF_blogshare() {
        return f_blogshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_blogshare
     *
     * @param f_blogshare the value for t_bd_orderform.f_blogshare
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_blogshare(Boolean f_blogshare) {
        this.f_blogshare = f_blogshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_baidushare
     *
     * @return the value of t_bd_orderform.f_baidushare
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Boolean getF_baidushare() {
        return f_baidushare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_baidushare
     *
     * @param f_baidushare the value for t_bd_orderform.f_baidushare
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_baidushare(Boolean f_baidushare) {
        this.f_baidushare = f_baidushare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_derate
     *
     * @return the value of t_bd_orderform.f_derate
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Double getF_derate() {
        return f_derate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_derate
     *
     * @param f_derate the value for t_bd_orderform.f_derate
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_derate(Double f_derate) {
        this.f_derate = f_derate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_stid
     *
     * @return the value of t_bd_orderform.f_stid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_stid() {
        return f_stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_stid
     *
     * @param f_stid the value for t_bd_orderform.f_stid
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_stid(String f_stid) {
        this.f_stid = f_stid == null ? null : f_stid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_licenceaddress
     *
     * @return the value of t_bd_orderform.f_licenceaddress
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_licenceaddress() {
        return f_licenceaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_licenceaddress
     *
     * @param f_licenceaddress the value for t_bd_orderform.f_licenceaddress
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_licenceaddress(String f_licenceaddress) {
        this.f_licenceaddress = f_licenceaddress == null ? null : f_licenceaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_orderform.f_desc
     *
     * @return the value of t_bd_orderform.f_desc
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getF_desc() {
        return f_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_orderform.f_desc
     *
     * @param f_desc the value for t_bd_orderform.f_desc
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setF_desc(String f_desc) {
        this.f_desc = f_desc == null ? null : f_desc.trim();
    }
}