package com.etong.pt.data.order;

import java.util.ArrayList;
import java.util.List;

public class OrderExample {
        protected Integer start;
        protected Integer limit;

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andF_ofidIsNull() {
            addCriterion("f_ofid is null");
            return (Criteria) this;
        }

        public Criteria andF_ofidIsNotNull() {
            addCriterion("f_ofid is not null");
            return (Criteria) this;
        }

        public Criteria andF_ofidEqualTo(Long value) {
            addCriterion("f_ofid =", value, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidNotEqualTo(Long value) {
            addCriterion("f_ofid <>", value, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidGreaterThan(Long value) {
            addCriterion("f_ofid >", value, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidGreaterThanOrEqualTo(Long value) {
            addCriterion("f_ofid >=", value, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidLessThan(Long value) {
            addCriterion("f_ofid <", value, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidLessThanOrEqualTo(Long value) {
            addCriterion("f_ofid <=", value, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidIn(List<Long> values) {
            addCriterion("f_ofid in", values, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidNotIn(List<Long> values) {
            addCriterion("f_ofid not in", values, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidBetween(Long value1, Long value2) {
            addCriterion("f_ofid between", value1, value2, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidNotBetween(Long value1, Long value2) {
            addCriterion("f_ofid not between", value1, value2, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeIsNull() {
            addCriterion("f_ofcode is null");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeIsNotNull() {
            addCriterion("f_ofcode is not null");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeEqualTo(String value) {
            addCriterion("f_ofcode =", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeNotEqualTo(String value) {
            addCriterion("f_ofcode <>", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeGreaterThan(String value) {
            addCriterion("f_ofcode >", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeGreaterThanOrEqualTo(String value) {
            addCriterion("f_ofcode >=", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeLessThan(String value) {
            addCriterion("f_ofcode <", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeLessThanOrEqualTo(String value) {
            addCriterion("f_ofcode <=", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeLike(String value) {
            addCriterion("f_ofcode like", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeNotLike(String value) {
            addCriterion("f_ofcode not like", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeIn(List<String> values) {
            addCriterion("f_ofcode in", values, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeNotIn(List<String> values) {
            addCriterion("f_ofcode not in", values, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeBetween(String value1, String value2) {
            addCriterion("f_ofcode between", value1, value2, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeNotBetween(String value1, String value2) {
            addCriterion("f_ofcode not between", value1, value2, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_midIsNull() {
            addCriterion("f_mid is null");
            return (Criteria) this;
        }

        public Criteria andF_midIsNotNull() {
            addCriterion("f_mid is not null");
            return (Criteria) this;
        }

        public Criteria andF_midEqualTo(Long value) {
            addCriterion("f_mid =", value, "f_mid");
            return (Criteria) this;
        }
        public Criteria andF_acidEqualTo(Long value) {
            addCriterion("f_acid =", value, "f_acid");
            return (Criteria) this;
        }

        public Criteria andF_midNotEqualTo(Long value) {
            addCriterion("f_mid <>", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midGreaterThan(Long value) {
            addCriterion("f_mid >", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midGreaterThanOrEqualTo(Long value) {
            addCriterion("f_mid >=", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midLessThan(Long value) {
            addCriterion("f_mid <", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midLessThanOrEqualTo(Long value) {
            addCriterion("f_mid <=", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midIn(List<Long> values) {
            addCriterion("f_mid in", values, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotIn(List<Long> values) {
            addCriterion("f_mid not in", values, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midBetween(Long value1, Long value2) {
            addCriterion("f_mid between", value1, value2, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotBetween(Long value1, Long value2) {
            addCriterion("f_mid not between", value1, value2, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_nameIsNull() {
            addCriterion("f_name is null");
            return (Criteria) this;
        }

        public Criteria andF_nameIsNotNull() {
            addCriterion("f_name is not null");
            return (Criteria) this;
        }

        public Criteria andF_nameEqualTo(String value) {
            addCriterion("f_name =", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotEqualTo(String value) {
            addCriterion("f_name <>", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameGreaterThan(String value) {
            addCriterion("f_name >", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameGreaterThanOrEqualTo(String value) {
            addCriterion("f_name >=", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameLessThan(String value) {
            addCriterion("f_name <", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameLessThanOrEqualTo(String value) {
            addCriterion("f_name <=", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameLike(String value) {
            addCriterion("f_name like", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotLike(String value) {
            addCriterion("f_name not like", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameIn(List<String> values) {
            addCriterion("f_name in", values, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotIn(List<String> values) {
            addCriterion("f_name not in", values, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameBetween(String value1, String value2) {
            addCriterion("f_name between", value1, value2, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotBetween(String value1, String value2) {
            addCriterion("f_name not between", value1, value2, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_phoneIsNull() {
            addCriterion("f_phone is null");
            return (Criteria) this;
        }

        public Criteria andF_phoneIsNotNull() {
            addCriterion("f_phone is not null");
            return (Criteria) this;
        }

        public Criteria andF_phoneEqualTo(String value) {
            addCriterion("f_phone =", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotEqualTo(String value) {
            addCriterion("f_phone <>", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneGreaterThan(String value) {
            addCriterion("f_phone >", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneGreaterThanOrEqualTo(String value) {
            addCriterion("f_phone >=", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLessThan(String value) {
            addCriterion("f_phone <", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLessThanOrEqualTo(String value) {
            addCriterion("f_phone <=", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLike(String value) {
            addCriterion("f_phone like", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotLike(String value) {
            addCriterion("f_phone not like", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneIn(List<String> values) {
            addCriterion("f_phone in", values, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotIn(List<String> values) {
            addCriterion("f_phone not in", values, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneBetween(String value1, String value2) {
            addCriterion("f_phone between", value1, value2, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotBetween(String value1, String value2) {
            addCriterion("f_phone not between", value1, value2, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_carbrandIsNull() {
            addCriterion("f_carbrand is null");
            return (Criteria) this;
        }

        public Criteria andF_carbrandIsNotNull() {
            addCriterion("f_carbrand is not null");
            return (Criteria) this;
        }

        public Criteria andF_carbrandEqualTo(String value) {
            addCriterion("f_carbrand =", value, "f_carbrand");
            return (Criteria) this;
        }

        public Criteria andF_carbrandNotEqualTo(String value) {
            addCriterion("f_carbrand <>", value, "f_carbrand");
            return (Criteria) this;
        }

        public Criteria andF_carbrandGreaterThan(String value) {
            addCriterion("f_carbrand >", value, "f_carbrand");
            return (Criteria) this;
        }

        public Criteria andF_carbrandGreaterThanOrEqualTo(String value) {
            addCriterion("f_carbrand >=", value, "f_carbrand");
            return (Criteria) this;
        }

        public Criteria andF_carbrandLessThan(String value) {
            addCriterion("f_carbrand <", value, "f_carbrand");
            return (Criteria) this;
        }

        public Criteria andF_carbrandLessThanOrEqualTo(String value) {
            addCriterion("f_carbrand <=", value, "f_carbrand");
            return (Criteria) this;
        }

        public Criteria andF_carbrandLike(String value) {
            addCriterion("f_carbrand like", value, "f_carbrand");
            return (Criteria) this;
        }

        public Criteria andF_carbrandNotLike(String value) {
            addCriterion("f_carbrand not like", value, "f_carbrand");
            return (Criteria) this;
        }

        public Criteria andF_carbrandIn(List<String> values) {
            addCriterion("f_carbrand in", values, "f_carbrand");
            return (Criteria) this;
        }

        public Criteria andF_carbrandNotIn(List<String> values) {
            addCriterion("f_carbrand not in", values, "f_carbrand");
            return (Criteria) this;
        }

        public Criteria andF_carbrandBetween(String value1, String value2) {
            addCriterion("f_carbrand between", value1, value2, "f_carbrand");
            return (Criteria) this;
        }

        public Criteria andF_carbrandNotBetween(String value1, String value2) {
            addCriterion("f_carbrand not between", value1, value2, "f_carbrand");
            return (Criteria) this;
        }

        public Criteria andF_carsetIsNull() {
            addCriterion("f_carset is null");
            return (Criteria) this;
        }

        public Criteria andF_carsetIsNotNull() {
            addCriterion("f_carset is not null");
            return (Criteria) this;
        }

        public Criteria andF_carsetEqualTo(String value) {
            addCriterion("f_carset =", value, "f_carset");
            return (Criteria) this;
        }

        public Criteria andF_carsetNotEqualTo(String value) {
            addCriterion("f_carset <>", value, "f_carset");
            return (Criteria) this;
        }

        public Criteria andF_carsetGreaterThan(String value) {
            addCriterion("f_carset >", value, "f_carset");
            return (Criteria) this;
        }

        public Criteria andF_carsetGreaterThanOrEqualTo(String value) {
            addCriterion("f_carset >=", value, "f_carset");
            return (Criteria) this;
        }

        public Criteria andF_carsetLessThan(String value) {
            addCriterion("f_carset <", value, "f_carset");
            return (Criteria) this;
        }

        public Criteria andF_carsetLessThanOrEqualTo(String value) {
            addCriterion("f_carset <=", value, "f_carset");
            return (Criteria) this;
        }

        public Criteria andF_carsetLike(String value) {
            addCriterion("f_carset like", value, "f_carset");
            return (Criteria) this;
        }

        public Criteria andF_carsetNotLike(String value) {
            addCriterion("f_carset not like", value, "f_carset");
            return (Criteria) this;
        }

        public Criteria andF_carsetIn(List<String> values) {
            addCriterion("f_carset in", values, "f_carset");
            return (Criteria) this;
        }

        public Criteria andF_carsetNotIn(List<String> values) {
            addCriterion("f_carset not in", values, "f_carset");
            return (Criteria) this;
        }

        public Criteria andF_carsetBetween(String value1, String value2) {
            addCriterion("f_carset between", value1, value2, "f_carset");
            return (Criteria) this;
        }

        public Criteria andF_carsetNotBetween(String value1, String value2) {
            addCriterion("f_carset not between", value1, value2, "f_carset");
            return (Criteria) this;
        }

        public Criteria andF_cartypeIsNull() {
            addCriterion("f_cartype is null");
            return (Criteria) this;
        }

        public Criteria andF_cartypeIsNotNull() {
            addCriterion("f_cartype is not null");
            return (Criteria) this;
        }

        public Criteria andF_cartypeEqualTo(String value) {
            addCriterion("f_cartype =", value, "f_cartype");
            return (Criteria) this;
        }

        public Criteria andF_cartypeNotEqualTo(String value) {
            addCriterion("f_cartype <>", value, "f_cartype");
            return (Criteria) this;
        }

        public Criteria andF_cartypeGreaterThan(String value) {
            addCriterion("f_cartype >", value, "f_cartype");
            return (Criteria) this;
        }

        public Criteria andF_cartypeGreaterThanOrEqualTo(String value) {
            addCriterion("f_cartype >=", value, "f_cartype");
            return (Criteria) this;
        }

        public Criteria andF_cartypeLessThan(String value) {
            addCriterion("f_cartype <", value, "f_cartype");
            return (Criteria) this;
        }

        public Criteria andF_cartypeLessThanOrEqualTo(String value) {
            addCriterion("f_cartype <=", value, "f_cartype");
            return (Criteria) this;
        }

        public Criteria andF_cartypeLike(String value) {
            addCriterion("f_cartype like", value, "f_cartype");
            return (Criteria) this;
        }

        public Criteria andF_cartypeNotLike(String value) {
            addCriterion("f_cartype not like", value, "f_cartype");
            return (Criteria) this;
        }

        public Criteria andF_cartypeIn(List<String> values) {
            addCriterion("f_cartype in", values, "f_cartype");
            return (Criteria) this;
        }

        public Criteria andF_cartypeNotIn(List<String> values) {
            addCriterion("f_cartype not in", values, "f_cartype");
            return (Criteria) this;
        }

        public Criteria andF_cartypeBetween(String value1, String value2) {
            addCriterion("f_cartype between", value1, value2, "f_cartype");
            return (Criteria) this;
        }

        public Criteria andF_cartypeNotBetween(String value1, String value2) {
            addCriterion("f_cartype not between", value1, value2, "f_cartype");
            return (Criteria) this;
        }

        public Criteria andF_carbrandidIsNull() {
            addCriterion("f_carbrandid is null");
            return (Criteria) this;
        }

        public Criteria andF_carbrandidIsNotNull() {
            addCriterion("f_carbrandid is not null");
            return (Criteria) this;
        }

        public Criteria andF_carbrandidEqualTo(Integer value) {
            addCriterion("f_carbrandid =", value, "f_carbrandid");
            return (Criteria) this;
        }

        public Criteria andF_carbrandidNotEqualTo(Integer value) {
            addCriterion("f_carbrandid <>", value, "f_carbrandid");
            return (Criteria) this;
        }

        public Criteria andF_carbrandidGreaterThan(Integer value) {
            addCriterion("f_carbrandid >", value, "f_carbrandid");
            return (Criteria) this;
        }

        public Criteria andF_carbrandidGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_carbrandid >=", value, "f_carbrandid");
            return (Criteria) this;
        }

        public Criteria andF_carbrandidLessThan(Integer value) {
            addCriterion("f_carbrandid <", value, "f_carbrandid");
            return (Criteria) this;
        }

        public Criteria andF_carbrandidLessThanOrEqualTo(Integer value) {
            addCriterion("f_carbrandid <=", value, "f_carbrandid");
            return (Criteria) this;
        }

        public Criteria andF_carbrandidIn(List<Integer> values) {
            addCriterion("f_carbrandid in", values, "f_carbrandid");
            return (Criteria) this;
        }

        public Criteria andF_carbrandidNotIn(List<Integer> values) {
            addCriterion("f_carbrandid not in", values, "f_carbrandid");
            return (Criteria) this;
        }

        public Criteria andF_carbrandidBetween(Integer value1, Integer value2) {
            addCriterion("f_carbrandid between", value1, value2, "f_carbrandid");
            return (Criteria) this;
        }

        public Criteria andF_carbrandidNotBetween(Integer value1, Integer value2) {
            addCriterion("f_carbrandid not between", value1, value2, "f_carbrandid");
            return (Criteria) this;
        }

        public Criteria andF_carsetidIsNull() {
            addCriterion("f_carsetid is null");
            return (Criteria) this;
        }

        public Criteria andF_carsetidIsNotNull() {
            addCriterion("f_carsetid is not null");
            return (Criteria) this;
        }

        public Criteria andF_carsetidEqualTo(Integer value) {
            addCriterion("f_carsetid =", value, "f_carsetid");
            return (Criteria) this;
        }

        public Criteria andF_carsetidNotEqualTo(Integer value) {
            addCriterion("f_carsetid <>", value, "f_carsetid");
            return (Criteria) this;
        }

        public Criteria andF_carsetidGreaterThan(Integer value) {
            addCriterion("f_carsetid >", value, "f_carsetid");
            return (Criteria) this;
        }

        public Criteria andF_carsetidGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_carsetid >=", value, "f_carsetid");
            return (Criteria) this;
        }

        public Criteria andF_carsetidLessThan(Integer value) {
            addCriterion("f_carsetid <", value, "f_carsetid");
            return (Criteria) this;
        }

        public Criteria andF_carsetidLessThanOrEqualTo(Integer value) {
            addCriterion("f_carsetid <=", value, "f_carsetid");
            return (Criteria) this;
        }

        public Criteria andF_carsetidIn(List<Integer> values) {
            addCriterion("f_carsetid in", values, "f_carsetid");
            return (Criteria) this;
        }

        public Criteria andF_carsetidNotIn(List<Integer> values) {
            addCriterion("f_carsetid not in", values, "f_carsetid");
            return (Criteria) this;
        }

        public Criteria andF_carsetidBetween(Integer value1, Integer value2) {
            addCriterion("f_carsetid between", value1, value2, "f_carsetid");
            return (Criteria) this;
        }

        public Criteria andF_carsetidNotBetween(Integer value1, Integer value2) {
            addCriterion("f_carsetid not between", value1, value2, "f_carsetid");
            return (Criteria) this;
        }

        public Criteria andF_cartypeidIsNull() {
            addCriterion("f_cartypeid is null");
            return (Criteria) this;
        }

        public Criteria andF_cartypeidIsNotNull() {
            addCriterion("f_cartypeid is not null");
            return (Criteria) this;
        }

        public Criteria andF_cartypeidEqualTo(Integer value) {
            addCriterion("f_cartypeid =", value, "f_cartypeid");
            return (Criteria) this;
        }

        public Criteria andF_cartypeidNotEqualTo(Integer value) {
            addCriterion("f_cartypeid <>", value, "f_cartypeid");
            return (Criteria) this;
        }

        public Criteria andF_cartypeidGreaterThan(Integer value) {
            addCriterion("f_cartypeid >", value, "f_cartypeid");
            return (Criteria) this;
        }

        public Criteria andF_cartypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_cartypeid >=", value, "f_cartypeid");
            return (Criteria) this;
        }

        public Criteria andF_cartypeidLessThan(Integer value) {
            addCriterion("f_cartypeid <", value, "f_cartypeid");
            return (Criteria) this;
        }

        public Criteria andF_cartypeidLessThanOrEqualTo(Integer value) {
            addCriterion("f_cartypeid <=", value, "f_cartypeid");
            return (Criteria) this;
        }

        public Criteria andF_cartypeidIn(List<Integer> values) {
            addCriterion("f_cartypeid in", values, "f_cartypeid");
            return (Criteria) this;
        }

        public Criteria andF_cartypeidNotIn(List<Integer> values) {
            addCriterion("f_cartypeid not in", values, "f_cartypeid");
            return (Criteria) this;
        }

        public Criteria andF_cartypeidBetween(Integer value1, Integer value2) {
            addCriterion("f_cartypeid between", value1, value2, "f_cartypeid");
            return (Criteria) this;
        }

        public Criteria andF_cartypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("f_cartypeid not between", value1, value2, "f_cartypeid");
            return (Criteria) this;
        }

        public Criteria andF_dvidIsNull() {
            addCriterion("f_dvid is null");
            return (Criteria) this;
        }

        public Criteria andF_dvidIsNotNull() {
            addCriterion("f_dvid is not null");
            return (Criteria) this;
        }

        public Criteria andF_dvidEqualTo(Long value) {
            addCriterion("f_dvid =", value, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidNotEqualTo(Long value) {
            addCriterion("f_dvid <>", value, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidGreaterThan(Long value) {
            addCriterion("f_dvid >", value, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidGreaterThanOrEqualTo(Long value) {
            addCriterion("f_dvid >=", value, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidLessThan(Long value) {
            addCriterion("f_dvid <", value, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidLessThanOrEqualTo(Long value) {
            addCriterion("f_dvid <=", value, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidIn(List<Long> values) {
            addCriterion("f_dvid in", values, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidNotIn(List<Long> values) {
            addCriterion("f_dvid not in", values, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidBetween(Long value1, Long value2) {
            addCriterion("f_dvid between", value1, value2, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidNotBetween(Long value1, Long value2) {
            addCriterion("f_dvid not between", value1, value2, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_operatoridIsNull() {
            addCriterion("f_operatorid is null");
            return (Criteria) this;
        }

        public Criteria andF_operatoridIsNotNull() {
            addCriterion("f_operatorid is not null");
            return (Criteria) this;
        }

        public Criteria andF_operatoridEqualTo(Long value) {
            addCriterion("f_operatorid =", value, "f_operatorid");
            return (Criteria) this;
        }

        public Criteria andF_operatoridNotEqualTo(Long value) {
            addCriterion("f_operatorid <>", value, "f_operatorid");
            return (Criteria) this;
        }

        public Criteria andF_operatoridGreaterThan(Long value) {
            addCriterion("f_operatorid >", value, "f_operatorid");
            return (Criteria) this;
        }

        public Criteria andF_operatoridGreaterThanOrEqualTo(Long value) {
            addCriterion("f_operatorid >=", value, "f_operatorid");
            return (Criteria) this;
        }

        public Criteria andF_operatoridLessThan(Long value) {
            addCriterion("f_operatorid <", value, "f_operatorid");
            return (Criteria) this;
        }

        public Criteria andF_operatoridLessThanOrEqualTo(Long value) {
            addCriterion("f_operatorid <=", value, "f_operatorid");
            return (Criteria) this;
        }

        public Criteria andF_operatoridIn(List<Long> values) {
            addCriterion("f_operatorid in", values, "f_operatorid");
            return (Criteria) this;
        }

        public Criteria andF_operatoridNotIn(List<Long> values) {
            addCriterion("f_operatorid not in", values, "f_operatorid");
            return (Criteria) this;
        }

        public Criteria andF_operatoridBetween(Long value1, Long value2) {
            addCriterion("f_operatorid between", value1, value2, "f_operatorid");
            return (Criteria) this;
        }

        public Criteria andF_operatoridNotBetween(Long value1, Long value2) {
            addCriterion("f_operatorid not between", value1, value2, "f_operatorid");
            return (Criteria) this;
        }

        public Criteria andF_operatorIsNull() {
            addCriterion("f_operator is null");
            return (Criteria) this;
        }

        public Criteria andF_operatorIsNotNull() {
            addCriterion("f_operator is not null");
            return (Criteria) this;
        }

        public Criteria andF_operatorEqualTo(String value) {
            addCriterion("f_operator =", value, "f_operator");
            return (Criteria) this;
        }

        public Criteria andF_operatorNotEqualTo(String value) {
            addCriterion("f_operator <>", value, "f_operator");
            return (Criteria) this;
        }

        public Criteria andF_operatorGreaterThan(String value) {
            addCriterion("f_operator >", value, "f_operator");
            return (Criteria) this;
        }

        public Criteria andF_operatorGreaterThanOrEqualTo(String value) {
            addCriterion("f_operator >=", value, "f_operator");
            return (Criteria) this;
        }

        public Criteria andF_operatorLessThan(String value) {
            addCriterion("f_operator <", value, "f_operator");
            return (Criteria) this;
        }

        public Criteria andF_operatorLessThanOrEqualTo(String value) {
            addCriterion("f_operator <=", value, "f_operator");
            return (Criteria) this;
        }

        public Criteria andF_operatorLike(String value) {
            addCriterion("f_operator like", value, "f_operator");
            return (Criteria) this;
        }

        public Criteria andF_operatorNotLike(String value) {
            addCriterion("f_operator not like", value, "f_operator");
            return (Criteria) this;
        }

        public Criteria andF_operatorIn(List<String> values) {
            addCriterion("f_operator in", values, "f_operator");
            return (Criteria) this;
        }

        public Criteria andF_operatorNotIn(List<String> values) {
            addCriterion("f_operator not in", values, "f_operator");
            return (Criteria) this;
        }

        public Criteria andF_operatorBetween(String value1, String value2) {
            addCriterion("f_operator between", value1, value2, "f_operator");
            return (Criteria) this;
        }

        public Criteria andF_operatorNotBetween(String value1, String value2) {
            addCriterion("f_operator not between", value1, value2, "f_operator");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeIsNull() {
            addCriterion("f_operatetime is null");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeIsNotNull() {
            addCriterion("f_operatetime is not null");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeEqualTo(Integer value) {
            addCriterion("f_operatetime =", value, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeNotEqualTo(Integer value) {
            addCriterion("f_operatetime <>", value, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeGreaterThan(Integer value) {
            addCriterion("f_operatetime >", value, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_operatetime >=", value, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeLessThan(Integer value) {
            addCriterion("f_operatetime <", value, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeLessThanOrEqualTo(Integer value) {
            addCriterion("f_operatetime <=", value, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeIn(List<Integer> values) {
            addCriterion("f_operatetime in", values, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeNotIn(List<Integer> values) {
            addCriterion("f_operatetime not in", values, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeBetween(Integer value1, Integer value2) {
            addCriterion("f_operatetime between", value1, value2, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("f_operatetime not between", value1, value2, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeIsNull() {
            addCriterion("f_createtime is null");
            return (Criteria) this;
        }

        public Criteria andF_createtimeIsNotNull() {
            addCriterion("f_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andF_createtimeEqualTo(Integer value) {
            addCriterion("f_createtime =", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeNotEqualTo(Integer value) {
            addCriterion("f_createtime <>", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeGreaterThan(Integer value) {
            addCriterion("f_createtime >", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_createtime >=", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeLessThan(Integer value) {
            addCriterion("f_createtime <", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeLessThanOrEqualTo(Integer value) {
            addCriterion("f_createtime <=", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeIn(List<Integer> values) {
            addCriterion("f_createtime in", values, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeNotIn(List<Integer> values) {
            addCriterion("f_createtime not in", values, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeBetween(Integer value1, Integer value2) {
            addCriterion("f_createtime between", value1, value2, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("f_createtime not between", value1, value2, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_statusIsNull() {
            addCriterion("f_status is null");
            return (Criteria) this;
        }

        public Criteria andF_statusIsNotNull() {
            addCriterion("f_status is not null");
            return (Criteria) this;
        }

        public Criteria andF_statusEqualTo(Integer value) {
            addCriterion("f_status =", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotEqualTo(Integer value) {
            addCriterion("f_status <>", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusGreaterThan(Integer value) {
            addCriterion("f_status >", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_status >=", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusLessThan(Integer value) {
            addCriterion("f_status <", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusLessThanOrEqualTo(Integer value) {
            addCriterion("f_status <=", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusIn(List<Integer> values) {
            addCriterion("f_status in", values, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotIn(List<Integer> values) {
            addCriterion("f_status not in", values, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusBetween(Integer value1, Integer value2) {
            addCriterion("f_status between", value1, value2, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("f_status not between", value1, value2, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_bottompriceIsNull() {
            addCriterion("f_bottomprice is null");
            return (Criteria) this;
        }

        public Criteria andF_bottompriceIsNotNull() {
            addCriterion("f_bottomprice is not null");
            return (Criteria) this;
        }

        public Criteria andF_bottompriceEqualTo(Double value) {
            addCriterion("f_bottomprice =", value, "f_bottomprice");
            return (Criteria) this;
        }

        public Criteria andF_bottompriceNotEqualTo(Double value) {
            addCriterion("f_bottomprice <>", value, "f_bottomprice");
            return (Criteria) this;
        }

        public Criteria andF_bottompriceGreaterThan(Double value) {
            addCriterion("f_bottomprice >", value, "f_bottomprice");
            return (Criteria) this;
        }

        public Criteria andF_bottompriceGreaterThanOrEqualTo(Double value) {
            addCriterion("f_bottomprice >=", value, "f_bottomprice");
            return (Criteria) this;
        }

        public Criteria andF_bottompriceLessThan(Double value) {
            addCriterion("f_bottomprice <", value, "f_bottomprice");
            return (Criteria) this;
        }

        public Criteria andF_bottompriceLessThanOrEqualTo(Double value) {
            addCriterion("f_bottomprice <=", value, "f_bottomprice");
            return (Criteria) this;
        }

        public Criteria andF_bottompriceIn(List<Double> values) {
            addCriterion("f_bottomprice in", values, "f_bottomprice");
            return (Criteria) this;
        }

        public Criteria andF_bottompriceNotIn(List<Double> values) {
            addCriterion("f_bottomprice not in", values, "f_bottomprice");
            return (Criteria) this;
        }

        public Criteria andF_bottompriceBetween(Double value1, Double value2) {
            addCriterion("f_bottomprice between", value1, value2, "f_bottomprice");
            return (Criteria) this;
        }

        public Criteria andF_bottompriceNotBetween(Double value1, Double value2) {
            addCriterion("f_bottomprice not between", value1, value2, "f_bottomprice");
            return (Criteria) this;
        }

        public Criteria andF_paymentsIsNull() {
            addCriterion("f_payments is null");
            return (Criteria) this;
        }

        public Criteria andF_paymentsIsNotNull() {
            addCriterion("f_payments is not null");
            return (Criteria) this;
        }

        public Criteria andF_paymentsEqualTo(Double value) {
            addCriterion("f_payments =", value, "f_payments");
            return (Criteria) this;
        }

        public Criteria andF_paymentsNotEqualTo(Double value) {
            addCriterion("f_payments <>", value, "f_payments");
            return (Criteria) this;
        }

        public Criteria andF_paymentsGreaterThan(Double value) {
            addCriterion("f_payments >", value, "f_payments");
            return (Criteria) this;
        }

        public Criteria andF_paymentsGreaterThanOrEqualTo(Double value) {
            addCriterion("f_payments >=", value, "f_payments");
            return (Criteria) this;
        }

        public Criteria andF_paymentsLessThan(Double value) {
            addCriterion("f_payments <", value, "f_payments");
            return (Criteria) this;
        }

        public Criteria andF_paymentsLessThanOrEqualTo(Double value) {
            addCriterion("f_payments <=", value, "f_payments");
            return (Criteria) this;
        }

        public Criteria andF_paymentsIn(List<Double> values) {
            addCriterion("f_payments in", values, "f_payments");
            return (Criteria) this;
        }

        public Criteria andF_paymentsNotIn(List<Double> values) {
            addCriterion("f_payments not in", values, "f_payments");
            return (Criteria) this;
        }

        public Criteria andF_paymentsBetween(Double value1, Double value2) {
            addCriterion("f_payments between", value1, value2, "f_payments");
            return (Criteria) this;
        }

        public Criteria andF_paymentsNotBetween(Double value1, Double value2) {
            addCriterion("f_payments not between", value1, value2, "f_payments");
            return (Criteria) this;
        }

        public Criteria andF_paymodeIsNull() {
            addCriterion("f_paymode is null");
            return (Criteria) this;
        }

        public Criteria andF_paymodeIsNotNull() {
            addCriterion("f_paymode is not null");
            return (Criteria) this;
        }

        public Criteria andF_paymodeEqualTo(Integer value) {
            addCriterion("f_paymode =", value, "f_paymode");
            return (Criteria) this;
        }

        public Criteria andF_paymodeNotEqualTo(Integer value) {
            addCriterion("f_paymode <>", value, "f_paymode");
            return (Criteria) this;
        }

        public Criteria andF_paymodeGreaterThan(Integer value) {
            addCriterion("f_paymode >", value, "f_paymode");
            return (Criteria) this;
        }

        public Criteria andF_paymodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_paymode >=", value, "f_paymode");
            return (Criteria) this;
        }

        public Criteria andF_paymodeLessThan(Integer value) {
            addCriterion("f_paymode <", value, "f_paymode");
            return (Criteria) this;
        }

        public Criteria andF_paymodeLessThanOrEqualTo(Integer value) {
            addCriterion("f_paymode <=", value, "f_paymode");
            return (Criteria) this;
        }

        public Criteria andF_paymodeIn(List<Integer> values) {
            addCriterion("f_paymode in", values, "f_paymode");
            return (Criteria) this;
        }

        public Criteria andF_paymodeNotIn(List<Integer> values) {
            addCriterion("f_paymode not in", values, "f_paymode");
            return (Criteria) this;
        }

        public Criteria andF_paymodeBetween(Integer value1, Integer value2) {
            addCriterion("f_paymode between", value1, value2, "f_paymode");
            return (Criteria) this;
        }

        public Criteria andF_paymodeNotBetween(Integer value1, Integer value2) {
            addCriterion("f_paymode not between", value1, value2, "f_paymode");
            return (Criteria) this;
        }

        public Criteria andF_payitemIsNull() {
            addCriterion("f_payitem is null");
            return (Criteria) this;
        }

        public Criteria andF_payitemIsNotNull() {
            addCriterion("f_payitem is not null");
            return (Criteria) this;
        }

        public Criteria andF_payitemEqualTo(Integer value) {
            addCriterion("f_payitem =", value, "f_payitem");
            return (Criteria) this;
        }

        public Criteria andF_payitemNotEqualTo(Integer value) {
            addCriterion("f_payitem <>", value, "f_payitem");
            return (Criteria) this;
        }

        public Criteria andF_payitemGreaterThan(Integer value) {
            addCriterion("f_payitem >", value, "f_payitem");
            return (Criteria) this;
        }

        public Criteria andF_payitemGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_payitem >=", value, "f_payitem");
            return (Criteria) this;
        }

        public Criteria andF_payitemLessThan(Integer value) {
            addCriterion("f_payitem <", value, "f_payitem");
            return (Criteria) this;
        }

        public Criteria andF_payitemLessThanOrEqualTo(Integer value) {
            addCriterion("f_payitem <=", value, "f_payitem");
            return (Criteria) this;
        }

        public Criteria andF_payitemIn(List<Integer> values) {
            addCriterion("f_payitem in", values, "f_payitem");
            return (Criteria) this;
        }

        public Criteria andF_payitemNotIn(List<Integer> values) {
            addCriterion("f_payitem not in", values, "f_payitem");
            return (Criteria) this;
        }

        public Criteria andF_payitemBetween(Integer value1, Integer value2) {
            addCriterion("f_payitem between", value1, value2, "f_payitem");
            return (Criteria) this;
        }

        public Criteria andF_payitemNotBetween(Integer value1, Integer value2) {
            addCriterion("f_payitem not between", value1, value2, "f_payitem");
            return (Criteria) this;
        }

        public Criteria andF_paycodeIsNull() {
            addCriterion("f_paycode is null");
            return (Criteria) this;
        }

        public Criteria andF_paycodeIsNotNull() {
            addCriterion("f_paycode is not null");
            return (Criteria) this;
        }

        public Criteria andF_paycodeEqualTo(String value) {
            addCriterion("f_paycode =", value, "f_paycode");
            return (Criteria) this;
        }

        public Criteria andF_paycodeNotEqualTo(String value) {
            addCriterion("f_paycode <>", value, "f_paycode");
            return (Criteria) this;
        }

        public Criteria andF_paycodeGreaterThan(String value) {
            addCriterion("f_paycode >", value, "f_paycode");
            return (Criteria) this;
        }

        public Criteria andF_paycodeGreaterThanOrEqualTo(String value) {
            addCriterion("f_paycode >=", value, "f_paycode");
            return (Criteria) this;
        }

        public Criteria andF_paycodeLessThan(String value) {
            addCriterion("f_paycode <", value, "f_paycode");
            return (Criteria) this;
        }

        public Criteria andF_paycodeLessThanOrEqualTo(String value) {
            addCriterion("f_paycode <=", value, "f_paycode");
            return (Criteria) this;
        }

        public Criteria andF_paycodeLike(String value) {
            addCriterion("f_paycode like", value, "f_paycode");
            return (Criteria) this;
        }

        public Criteria andF_paycodeNotLike(String value) {
            addCriterion("f_paycode not like", value, "f_paycode");
            return (Criteria) this;
        }

        public Criteria andF_paycodeIn(List<String> values) {
            addCriterion("f_paycode in", values, "f_paycode");
            return (Criteria) this;
        }

        public Criteria andF_paycodeNotIn(List<String> values) {
            addCriterion("f_paycode not in", values, "f_paycode");
            return (Criteria) this;
        }

        public Criteria andF_paycodeBetween(String value1, String value2) {
            addCriterion("f_paycode between", value1, value2, "f_paycode");
            return (Criteria) this;
        }

        public Criteria andF_paycodeNotBetween(String value1, String value2) {
            addCriterion("f_paycode not between", value1, value2, "f_paycode");
            return (Criteria) this;
        }

        public Criteria andF_paytimeIsNull() {
            addCriterion("f_paytime is null");
            return (Criteria) this;
        }

        public Criteria andF_paytimeIsNotNull() {
            addCriterion("f_paytime is not null");
            return (Criteria) this;
        }

        public Criteria andF_paytimeEqualTo(Integer value) {
            addCriterion("f_paytime =", value, "f_paytime");
            return (Criteria) this;
        }

        public Criteria andF_paytimeNotEqualTo(Integer value) {
            addCriterion("f_paytime <>", value, "f_paytime");
            return (Criteria) this;
        }

        public Criteria andF_paytimeGreaterThan(Integer value) {
            addCriterion("f_paytime >", value, "f_paytime");
            return (Criteria) this;
        }

        public Criteria andF_paytimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_paytime >=", value, "f_paytime");
            return (Criteria) this;
        }

        public Criteria andF_paytimeLessThan(Integer value) {
            addCriterion("f_paytime <", value, "f_paytime");
            return (Criteria) this;
        }

        public Criteria andF_paytimeLessThanOrEqualTo(Integer value) {
            addCriterion("f_paytime <=", value, "f_paytime");
            return (Criteria) this;
        }

        public Criteria andF_paytimeIn(List<Integer> values) {
            addCriterion("f_paytime in", values, "f_paytime");
            return (Criteria) this;
        }

        public Criteria andF_paytimeNotIn(List<Integer> values) {
            addCriterion("f_paytime not in", values, "f_paytime");
            return (Criteria) this;
        }

        public Criteria andF_paytimeBetween(Integer value1, Integer value2) {
            addCriterion("f_paytime between", value1, value2, "f_paytime");
            return (Criteria) this;
        }

        public Criteria andF_paytimeNotBetween(Integer value1, Integer value2) {
            addCriterion("f_paytime not between", value1, value2, "f_paytime");
            return (Criteria) this;
        }

        public Criteria andF_ncidIsNull() {
            addCriterion("f_ncid is null");
            return (Criteria) this;
        }

        public Criteria andF_ncidIsNotNull() {
            addCriterion("f_ncid is not null");
            return (Criteria) this;
        }

        public Criteria andF_ncidEqualTo(Integer value) {
            addCriterion("f_ncid =", value, "f_ncid");
            return (Criteria) this;
        }

        public Criteria andF_ncidNotEqualTo(Integer value) {
            addCriterion("f_ncid <>", value, "f_ncid");
            return (Criteria) this;
        }

        public Criteria andF_ncidGreaterThan(Integer value) {
            addCriterion("f_ncid >", value, "f_ncid");
            return (Criteria) this;
        }

        public Criteria andF_ncidGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_ncid >=", value, "f_ncid");
            return (Criteria) this;
        }

        public Criteria andF_ncidLessThan(Integer value) {
            addCriterion("f_ncid <", value, "f_ncid");
            return (Criteria) this;
        }

        public Criteria andF_ncidLessThanOrEqualTo(Integer value) {
            addCriterion("f_ncid <=", value, "f_ncid");
            return (Criteria) this;
        }

        public Criteria andF_ncidIn(List<Integer> values) {
            addCriterion("f_ncid in", values, "f_ncid");
            return (Criteria) this;
        }

        public Criteria andF_ncidNotIn(List<Integer> values) {
            addCriterion("f_ncid not in", values, "f_ncid");
            return (Criteria) this;
        }

        public Criteria andF_ncidBetween(Integer value1, Integer value2) {
            addCriterion("f_ncid between", value1, value2, "f_ncid");
            return (Criteria) this;
        }

        public Criteria andF_ncidNotBetween(Integer value1, Integer value2) {
            addCriterion("f_ncid not between", value1, value2, "f_ncid");
            return (Criteria) this;
        }

        public Criteria andF_purchasewayIsNull() {
            addCriterion("f_purchaseway is null");
            return (Criteria) this;
        }

        public Criteria andF_purchasewayIsNotNull() {
            addCriterion("f_purchaseway is not null");
            return (Criteria) this;
        }

        public Criteria andF_purchasewayEqualTo(Integer value) {
            addCriterion("f_purchaseway =", value, "f_purchaseway");
            return (Criteria) this;
        }

        public Criteria andF_purchasewayNotEqualTo(Integer value) {
            addCriterion("f_purchaseway <>", value, "f_purchaseway");
            return (Criteria) this;
        }

        public Criteria andF_purchasewayGreaterThan(Integer value) {
            addCriterion("f_purchaseway >", value, "f_purchaseway");
            return (Criteria) this;
        }

        public Criteria andF_purchasewayGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_purchaseway >=", value, "f_purchaseway");
            return (Criteria) this;
        }

        public Criteria andF_purchasewayLessThan(Integer value) {
            addCriterion("f_purchaseway <", value, "f_purchaseway");
            return (Criteria) this;
        }

        public Criteria andF_purchasewayLessThanOrEqualTo(Integer value) {
            addCriterion("f_purchaseway <=", value, "f_purchaseway");
            return (Criteria) this;
        }

        public Criteria andF_purchasewayIn(List<Integer> values) {
            addCriterion("f_purchaseway in", values, "f_purchaseway");
            return (Criteria) this;
        }

        public Criteria andF_purchasewayNotIn(List<Integer> values) {
            addCriterion("f_purchaseway not in", values, "f_purchaseway");
            return (Criteria) this;
        }

        public Criteria andF_purchasewayBetween(Integer value1, Integer value2) {
            addCriterion("f_purchaseway between", value1, value2, "f_purchaseway");
            return (Criteria) this;
        }

        public Criteria andF_purchasewayNotBetween(Integer value1, Integer value2) {
            addCriterion("f_purchaseway not between", value1, value2, "f_purchaseway");
            return (Criteria) this;
        }

        public Criteria andF_expecttimeIsNull() {
            addCriterion("f_expecttime is null");
            return (Criteria) this;
        }

        public Criteria andF_expecttimeIsNotNull() {
            addCriterion("f_expecttime is not null");
            return (Criteria) this;
        }

        public Criteria andF_expecttimeEqualTo(String value) {
            addCriterion("f_expecttime =", value, "f_expecttime");
            return (Criteria) this;
        }

        public Criteria andF_expecttimeNotEqualTo(String value) {
            addCriterion("f_expecttime <>", value, "f_expecttime");
            return (Criteria) this;
        }

        public Criteria andF_expecttimeGreaterThan(String value) {
            addCriterion("f_expecttime >", value, "f_expecttime");
            return (Criteria) this;
        }

        public Criteria andF_expecttimeGreaterThanOrEqualTo(String value) {
            addCriterion("f_expecttime >=", value, "f_expecttime");
            return (Criteria) this;
        }

        public Criteria andF_expecttimeLessThan(String value) {
            addCriterion("f_expecttime <", value, "f_expecttime");
            return (Criteria) this;
        }

        public Criteria andF_expecttimeLessThanOrEqualTo(String value) {
            addCriterion("f_expecttime <=", value, "f_expecttime");
            return (Criteria) this;
        }

        public Criteria andF_expecttimeIn(List<String> values) {
            addCriterion("f_expecttime in", values, "f_expecttime");
            return (Criteria) this;
        }

        public Criteria andF_expecttimeNotIn(List<String> values) {
            addCriterion("f_expecttime not in", values, "f_expecttime");
            return (Criteria) this;
        }

        public Criteria andF_expecttimeBetween(String value1, String value2) {
            addCriterion("f_expecttime between", value1, value2, "f_expecttime");
            return (Criteria) this;
        }

        public Criteria andF_expecttimeNotBetween(String value1, String value2) {
            addCriterion("f_expecttime not between", value1, value2, "f_expecttime");
            return (Criteria) this;
        }

        public Criteria andF_ncnameIsNull() {
            addCriterion("f_ncname is null");
            return (Criteria) this;
        }

        public Criteria andF_ncnameIsNotNull() {
            addCriterion("f_ncname is not null");
            return (Criteria) this;
        }

        public Criteria andF_ncnameEqualTo(String value) {
            addCriterion("f_ncname =", value, "f_ncname");
            return (Criteria) this;
        }

        public Criteria andF_ncnameNotEqualTo(String value) {
            addCriterion("f_ncname <>", value, "f_ncname");
            return (Criteria) this;
        }

        public Criteria andF_ncnameGreaterThan(String value) {
            addCriterion("f_ncname >", value, "f_ncname");
            return (Criteria) this;
        }

        public Criteria andF_ncnameGreaterThanOrEqualTo(String value) {
            addCriterion("f_ncname >=", value, "f_ncname");
            return (Criteria) this;
        }

        public Criteria andF_ncnameLessThan(String value) {
            addCriterion("f_ncname <", value, "f_ncname");
            return (Criteria) this;
        }

        public Criteria andF_ncnameLessThanOrEqualTo(String value) {
            addCriterion("f_ncname <=", value, "f_ncname");
            return (Criteria) this;
        }

        public Criteria andF_ncnameLike(String value) {
            addCriterion("f_ncname like", value, "f_ncname");
            return (Criteria) this;
        }

        public Criteria andF_ncnameNotLike(String value) {
            addCriterion("f_ncname not like", value, "f_ncname");
            return (Criteria) this;
        }

        public Criteria andF_ncnameIn(List<String> values) {
            addCriterion("f_ncname in", values, "f_ncname");
            return (Criteria) this;
        }

        public Criteria andF_ncnameNotIn(List<String> values) {
            addCriterion("f_ncname not in", values, "f_ncname");
            return (Criteria) this;
        }

        public Criteria andF_ncnameBetween(String value1, String value2) {
            addCriterion("f_ncname between", value1, value2, "f_ncname");
            return (Criteria) this;
        }

        public Criteria andF_ncnameNotBetween(String value1, String value2) {
            addCriterion("f_ncname not between", value1, value2, "f_ncname");
            return (Criteria) this;
        }

        public Criteria andF_salemanIsNull() {
            addCriterion("f_saleman is null");
            return (Criteria) this;
        }

        public Criteria andF_salemanIsNotNull() {
            addCriterion("f_saleman is not null");
            return (Criteria) this;
        }

        public Criteria andF_salemanEqualTo(String value) {
            addCriterion("f_saleman =", value, "f_saleman");
            return (Criteria) this;
        }

        public Criteria andF_salemanNotEqualTo(String value) {
            addCriterion("f_saleman <>", value, "f_saleman");
            return (Criteria) this;
        }

        public Criteria andF_salemanGreaterThan(String value) {
            addCriterion("f_saleman >", value, "f_saleman");
            return (Criteria) this;
        }

        public Criteria andF_salemanGreaterThanOrEqualTo(String value) {
            addCriterion("f_saleman >=", value, "f_saleman");
            return (Criteria) this;
        }

        public Criteria andF_salemanLessThan(String value) {
            addCriterion("f_saleman <", value, "f_saleman");
            return (Criteria) this;
        }

        public Criteria andF_salemanLessThanOrEqualTo(String value) {
            addCriterion("f_saleman <=", value, "f_saleman");
            return (Criteria) this;
        }

        public Criteria andF_salemanLike(String value) {
            addCriterion("f_saleman like", value, "f_saleman");
            return (Criteria) this;
        }

        public Criteria andF_salemanNotLike(String value) {
            addCriterion("f_saleman not like", value, "f_saleman");
            return (Criteria) this;
        }

        public Criteria andF_salemanIn(List<String> values) {
            addCriterion("f_saleman in", values, "f_saleman");
            return (Criteria) this;
        }

        public Criteria andF_salemanNotIn(List<String> values) {
            addCriterion("f_saleman not in", values, "f_saleman");
            return (Criteria) this;
        }

        public Criteria andF_salemanBetween(String value1, String value2) {
            addCriterion("f_saleman between", value1, value2, "f_saleman");
            return (Criteria) this;
        }

        public Criteria andF_salemanNotBetween(String value1, String value2) {
            addCriterion("f_saleman not between", value1, value2, "f_saleman");
            return (Criteria) this;
        }

        public Criteria andF_salephoneIsNull() {
            addCriterion("f_salephone is null");
            return (Criteria) this;
        }

        public Criteria andF_salephoneIsNotNull() {
            addCriterion("f_salephone is not null");
            return (Criteria) this;
        }

        public Criteria andF_salephoneEqualTo(String value) {
            addCriterion("f_salephone =", value, "f_salephone");
            return (Criteria) this;
        }

        public Criteria andF_salephoneNotEqualTo(String value) {
            addCriterion("f_salephone <>", value, "f_salephone");
            return (Criteria) this;
        }

        public Criteria andF_salephoneGreaterThan(String value) {
            addCriterion("f_salephone >", value, "f_salephone");
            return (Criteria) this;
        }

        public Criteria andF_salephoneGreaterThanOrEqualTo(String value) {
            addCriterion("f_salephone >=", value, "f_salephone");
            return (Criteria) this;
        }

        public Criteria andF_salephoneLessThan(String value) {
            addCriterion("f_salephone <", value, "f_salephone");
            return (Criteria) this;
        }

        public Criteria andF_salephoneLessThanOrEqualTo(String value) {
            addCriterion("f_salephone <=", value, "f_salephone");
            return (Criteria) this;
        }

        public Criteria andF_salephoneLike(String value) {
            addCriterion("f_salephone like", value, "f_salephone");
            return (Criteria) this;
        }

        public Criteria andF_salephoneNotLike(String value) {
            addCriterion("f_salephone not like", value, "f_salephone");
            return (Criteria) this;
        }

        public Criteria andF_salephoneIn(List<String> values) {
            addCriterion("f_salephone in", values, "f_salephone");
            return (Criteria) this;
        }

        public Criteria andF_salephoneNotIn(List<String> values) {
            addCriterion("f_salephone not in", values, "f_salephone");
            return (Criteria) this;
        }

        public Criteria andF_salephoneBetween(String value1, String value2) {
            addCriterion("f_salephone between", value1, value2, "f_salephone");
            return (Criteria) this;
        }

        public Criteria andF_salephoneNotBetween(String value1, String value2) {
            addCriterion("f_salephone not between", value1, value2, "f_salephone");
            return (Criteria) this;
        }

        public Criteria andF_colorIsNull() {
            addCriterion("f_color is null");
            return (Criteria) this;
        }

        public Criteria andF_colorIsNotNull() {
            addCriterion("f_color is not null");
            return (Criteria) this;
        }

        public Criteria andF_colorEqualTo(String value) {
            addCriterion("f_color =", value, "f_color");
            return (Criteria) this;
        }

        public Criteria andF_colorNotEqualTo(String value) {
            addCriterion("f_color <>", value, "f_color");
            return (Criteria) this;
        }

        public Criteria andF_colorGreaterThan(String value) {
            addCriterion("f_color >", value, "f_color");
            return (Criteria) this;
        }

        public Criteria andF_colorGreaterThanOrEqualTo(String value) {
            addCriterion("f_color >=", value, "f_color");
            return (Criteria) this;
        }

        public Criteria andF_colorLessThan(String value) {
            addCriterion("f_color <", value, "f_color");
            return (Criteria) this;
        }

        public Criteria andF_colorLessThanOrEqualTo(String value) {
            addCriterion("f_color <=", value, "f_color");
            return (Criteria) this;
        }

        public Criteria andF_colorLike(String value) {
            addCriterion("f_color like", value, "f_color");
            return (Criteria) this;
        }

        public Criteria andF_colorNotLike(String value) {
            addCriterion("f_color not like", value, "f_color");
            return (Criteria) this;
        }

        public Criteria andF_colorIn(List<String> values) {
            addCriterion("f_color in", values, "f_color");
            return (Criteria) this;
        }

        public Criteria andF_colorNotIn(List<String> values) {
            addCriterion("f_color not in", values, "f_color");
            return (Criteria) this;
        }

        public Criteria andF_colorBetween(String value1, String value2) {
            addCriterion("f_color between", value1, value2, "f_color");
            return (Criteria) this;
        }

        public Criteria andF_colorNotBetween(String value1, String value2) {
            addCriterion("f_color not between", value1, value2, "f_color");
            return (Criteria) this;
        }

        public Criteria andF_typeIsNull() {
            addCriterion("f_type is null");
            return (Criteria) this;
        }

        public Criteria andF_typeIsNotNull() {
            addCriterion("f_type is not null");
            return (Criteria) this;
        }

        public Criteria andF_typeEqualTo(Integer value) {
            addCriterion("f_type =", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeNotEqualTo(Integer value) {
            addCriterion("f_type <>", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeGreaterThan(Integer value) {
            addCriterion("f_type >", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_type >=", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeLessThan(Integer value) {
            addCriterion("f_type <", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeLessThanOrEqualTo(Integer value) {
            addCriterion("f_type <=", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeIn(List<Integer> values) {
            addCriterion("f_type in", values, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeNotIn(List<Integer> values) {
            addCriterion("f_type not in", values, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeBetween(Integer value1, Integer value2) {
            addCriterion("f_type between", value1, value2, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("f_type not between", value1, value2, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_dcidIsNull() {
            addCriterion("f_dcid is null");
            return (Criteria) this;
        }

        public Criteria andF_dcidIsNotNull() {
            addCriterion("f_dcid is not null");
            return (Criteria) this;
        }

        public Criteria andF_dcidEqualTo(Long value) {
            addCriterion("f_dcid =", value, "f_dcid");
            return (Criteria) this;
        }

        public Criteria andF_dcidNotEqualTo(Long value) {
            addCriterion("f_dcid <>", value, "f_dcid");
            return (Criteria) this;
        }

        public Criteria andF_dcidGreaterThan(Long value) {
            addCriterion("f_dcid >", value, "f_dcid");
            return (Criteria) this;
        }

        public Criteria andF_dcidGreaterThanOrEqualTo(Long value) {
            addCriterion("f_dcid >=", value, "f_dcid");
            return (Criteria) this;
        }

        public Criteria andF_dcidLessThan(Long value) {
            addCriterion("f_dcid <", value, "f_dcid");
            return (Criteria) this;
        }

        public Criteria andF_dcidLessThanOrEqualTo(Long value) {
            addCriterion("f_dcid <=", value, "f_dcid");
            return (Criteria) this;
        }

        public Criteria andF_dcidIn(List<Long> values) {
            addCriterion("f_dcid in", values, "f_dcid");
            return (Criteria) this;
        }

        public Criteria andF_dcidNotIn(List<Long> values) {
            addCriterion("f_dcid not in", values, "f_dcid");
            return (Criteria) this;
        }

        public Criteria andF_dcidBetween(Long value1, Long value2) {
            addCriterion("f_dcid between", value1, value2, "f_dcid");
            return (Criteria) this;
        }

        public Criteria andF_dcidNotBetween(Long value1, Long value2) {
            addCriterion("f_dcid not between", value1, value2, "f_dcid");
            return (Criteria) this;
        }

        public Criteria andF_validIsNull() {
            addCriterion("f_valid is null");
            return (Criteria) this;
        }

        public Criteria andF_validIsNotNull() {
            addCriterion("f_valid is not null");
            return (Criteria) this;
        }

        public Criteria andF_validEqualTo(Boolean value) {
            addCriterion("f_valid =", value, "f_valid");
            return (Criteria) this;
        }

        public Criteria andF_validNotEqualTo(Boolean value) {
            addCriterion("f_valid <>", value, "f_valid");
            return (Criteria) this;
        }

        public Criteria andF_validGreaterThan(Boolean value) {
            addCriterion("f_valid >", value, "f_valid");
            return (Criteria) this;
        }

        public Criteria andF_validGreaterThanOrEqualTo(Boolean value) {
            addCriterion("f_valid >=", value, "f_valid");
            return (Criteria) this;
        }

        public Criteria andF_validLessThan(Boolean value) {
            addCriterion("f_valid <", value, "f_valid");
            return (Criteria) this;
        }

        public Criteria andF_validLessThanOrEqualTo(Boolean value) {
            addCriterion("f_valid <=", value, "f_valid");
            return (Criteria) this;
        }

        public Criteria andF_validIn(List<Boolean> values) {
            addCriterion("f_valid in", values, "f_valid");
            return (Criteria) this;
        }

        public Criteria andF_validNotIn(List<Boolean> values) {
            addCriterion("f_valid not in", values, "f_valid");
            return (Criteria) this;
        }

        public Criteria andF_validBetween(Boolean value1, Boolean value2) {
            addCriterion("f_valid between", value1, value2, "f_valid");
            return (Criteria) this;
        }

        public Criteria andF_validNotBetween(Boolean value1, Boolean value2) {
            addCriterion("f_valid not between", value1, value2, "f_valid");
            return (Criteria) this;
        }

        public Criteria andF_wechatshareIsNull() {
            addCriterion("f_wechatshare is null");
            return (Criteria) this;
        }

        public Criteria andF_wechatshareIsNotNull() {
            addCriterion("f_wechatshare is not null");
            return (Criteria) this;
        }

        public Criteria andF_wechatshareEqualTo(Boolean value) {
            addCriterion("f_wechatshare =", value, "f_wechatshare");
            return (Criteria) this;
        }

        public Criteria andF_wechatshareNotEqualTo(Boolean value) {
            addCriterion("f_wechatshare <>", value, "f_wechatshare");
            return (Criteria) this;
        }

        public Criteria andF_wechatshareGreaterThan(Boolean value) {
            addCriterion("f_wechatshare >", value, "f_wechatshare");
            return (Criteria) this;
        }

        public Criteria andF_wechatshareGreaterThanOrEqualTo(Boolean value) {
            addCriterion("f_wechatshare >=", value, "f_wechatshare");
            return (Criteria) this;
        }

        public Criteria andF_wechatshareLessThan(Boolean value) {
            addCriterion("f_wechatshare <", value, "f_wechatshare");
            return (Criteria) this;
        }

        public Criteria andF_wechatshareLessThanOrEqualTo(Boolean value) {
            addCriterion("f_wechatshare <=", value, "f_wechatshare");
            return (Criteria) this;
        }

        public Criteria andF_wechatshareIn(List<Boolean> values) {
            addCriterion("f_wechatshare in", values, "f_wechatshare");
            return (Criteria) this;
        }

        public Criteria andF_wechatshareNotIn(List<Boolean> values) {
            addCriterion("f_wechatshare not in", values, "f_wechatshare");
            return (Criteria) this;
        }

        public Criteria andF_wechatshareBetween(Boolean value1, Boolean value2) {
            addCriterion("f_wechatshare between", value1, value2, "f_wechatshare");
            return (Criteria) this;
        }

        public Criteria andF_wechatshareNotBetween(Boolean value1, Boolean value2) {
            addCriterion("f_wechatshare not between", value1, value2, "f_wechatshare");
            return (Criteria) this;
        }

        public Criteria andF_blogshareIsNull() {
            addCriterion("f_blogshare is null");
            return (Criteria) this;
        }

        public Criteria andF_blogshareIsNotNull() {
            addCriterion("f_blogshare is not null");
            return (Criteria) this;
        }

        public Criteria andF_blogshareEqualTo(Boolean value) {
            addCriterion("f_blogshare =", value, "f_blogshare");
            return (Criteria) this;
        }

        public Criteria andF_blogshareNotEqualTo(Boolean value) {
            addCriterion("f_blogshare <>", value, "f_blogshare");
            return (Criteria) this;
        }

        public Criteria andF_blogshareGreaterThan(Boolean value) {
            addCriterion("f_blogshare >", value, "f_blogshare");
            return (Criteria) this;
        }

        public Criteria andF_blogshareGreaterThanOrEqualTo(Boolean value) {
            addCriterion("f_blogshare >=", value, "f_blogshare");
            return (Criteria) this;
        }

        public Criteria andF_blogshareLessThan(Boolean value) {
            addCriterion("f_blogshare <", value, "f_blogshare");
            return (Criteria) this;
        }

        public Criteria andF_blogshareLessThanOrEqualTo(Boolean value) {
            addCriterion("f_blogshare <=", value, "f_blogshare");
            return (Criteria) this;
        }

        public Criteria andF_blogshareIn(List<Boolean> values) {
            addCriterion("f_blogshare in", values, "f_blogshare");
            return (Criteria) this;
        }

        public Criteria andF_blogshareNotIn(List<Boolean> values) {
            addCriterion("f_blogshare not in", values, "f_blogshare");
            return (Criteria) this;
        }

        public Criteria andF_blogshareBetween(Boolean value1, Boolean value2) {
            addCriterion("f_blogshare between", value1, value2, "f_blogshare");
            return (Criteria) this;
        }

        public Criteria andF_blogshareNotBetween(Boolean value1, Boolean value2) {
            addCriterion("f_blogshare not between", value1, value2, "f_blogshare");
            return (Criteria) this;
        }

        public Criteria andF_baidushareIsNull() {
            addCriterion("f_baidushare is null");
            return (Criteria) this;
        }

        public Criteria andF_baidushareIsNotNull() {
            addCriterion("f_baidushare is not null");
            return (Criteria) this;
        }

        public Criteria andF_baidushareEqualTo(Boolean value) {
            addCriterion("f_baidushare =", value, "f_baidushare");
            return (Criteria) this;
        }

        public Criteria andF_baidushareNotEqualTo(Boolean value) {
            addCriterion("f_baidushare <>", value, "f_baidushare");
            return (Criteria) this;
        }

        public Criteria andF_baidushareGreaterThan(Boolean value) {
            addCriterion("f_baidushare >", value, "f_baidushare");
            return (Criteria) this;
        }

        public Criteria andF_baidushareGreaterThanOrEqualTo(Boolean value) {
            addCriterion("f_baidushare >=", value, "f_baidushare");
            return (Criteria) this;
        }

        public Criteria andF_baidushareLessThan(Boolean value) {
            addCriterion("f_baidushare <", value, "f_baidushare");
            return (Criteria) this;
        }

        public Criteria andF_baidushareLessThanOrEqualTo(Boolean value) {
            addCriterion("f_baidushare <=", value, "f_baidushare");
            return (Criteria) this;
        }

        public Criteria andF_baidushareIn(List<Boolean> values) {
            addCriterion("f_baidushare in", values, "f_baidushare");
            return (Criteria) this;
        }

        public Criteria andF_baidushareNotIn(List<Boolean> values) {
            addCriterion("f_baidushare not in", values, "f_baidushare");
            return (Criteria) this;
        }

        public Criteria andF_baidushareBetween(Boolean value1, Boolean value2) {
            addCriterion("f_baidushare between", value1, value2, "f_baidushare");
            return (Criteria) this;
        }

        public Criteria andF_baidushareNotBetween(Boolean value1, Boolean value2) {
            addCriterion("f_baidushare not between", value1, value2, "f_baidushare");
            return (Criteria) this;
        }

        public Criteria andF_derateIsNull() {
            addCriterion("f_derate is null");
            return (Criteria) this;
        }

        public Criteria andF_derateIsNotNull() {
            addCriterion("f_derate is not null");
            return (Criteria) this;
        }

        public Criteria andF_derateEqualTo(Double value) {
            addCriterion("f_derate =", value, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateNotEqualTo(Double value) {
            addCriterion("f_derate <>", value, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateGreaterThan(Double value) {
            addCriterion("f_derate >", value, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateGreaterThanOrEqualTo(Double value) {
            addCriterion("f_derate >=", value, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateLessThan(Double value) {
            addCriterion("f_derate <", value, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateLessThanOrEqualTo(Double value) {
            addCriterion("f_derate <=", value, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateIn(List<Double> values) {
            addCriterion("f_derate in", values, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateNotIn(List<Double> values) {
            addCriterion("f_derate not in", values, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateBetween(Double value1, Double value2) {
            addCriterion("f_derate between", value1, value2, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateNotBetween(Double value1, Double value2) {
            addCriterion("f_derate not between", value1, value2, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_stidIsNull() {
            addCriterion("f_stid is null");
            return (Criteria) this;
        }

        public Criteria andF_stidIsNotNull() {
            addCriterion("f_stid is not null");
            return (Criteria) this;
        }

        public Criteria andF_stidEqualTo(String value) {
            addCriterion("f_stid =", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidNotEqualTo(String value) {
            addCriterion("f_stid <>", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidGreaterThan(String value) {
            addCriterion("f_stid >", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidGreaterThanOrEqualTo(String value) {
            addCriterion("f_stid >=", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidLessThan(String value) {
            addCriterion("f_stid <", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidLessThanOrEqualTo(String value) {
            addCriterion("f_stid <=", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidLike(String value) {
            addCriterion("f_stid like", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidNotLike(String value) {
            addCriterion("f_stid not like", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidIn(List<String> values) {
            addCriterion("f_stid in", values, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidNotIn(List<String> values) {
            addCriterion("f_stid not in", values, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidBetween(String value1, String value2) {
            addCriterion("f_stid between", value1, value2, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidNotBetween(String value1, String value2) {
            addCriterion("f_stid not between", value1, value2, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressIsNull() {
            addCriterion("f_licenceaddress is null");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressIsNotNull() {
            addCriterion("f_licenceaddress is not null");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressEqualTo(String value) {
            addCriterion("f_licenceaddress =", value, "f_licenceaddress");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressNotEqualTo(String value) {
            addCriterion("f_licenceaddress <>", value, "f_licenceaddress");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressGreaterThan(String value) {
            addCriterion("f_licenceaddress >", value, "f_licenceaddress");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressGreaterThanOrEqualTo(String value) {
            addCriterion("f_licenceaddress >=", value, "f_licenceaddress");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressLessThan(String value) {
            addCriterion("f_licenceaddress <", value, "f_licenceaddress");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressLessThanOrEqualTo(String value) {
            addCriterion("f_licenceaddress <=", value, "f_licenceaddress");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressLike(String value) {
            addCriterion("f_licenceaddress like", value, "f_licenceaddress");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressNotLike(String value) {
            addCriterion("f_licenceaddress not like", value, "f_licenceaddress");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressIn(List<String> values) {
            addCriterion("f_licenceaddress in", values, "f_licenceaddress");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressNotIn(List<String> values) {
            addCriterion("f_licenceaddress not in", values, "f_licenceaddress");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressBetween(String value1, String value2) {
            addCriterion("f_licenceaddress between", value1, value2, "f_licenceaddress");
            return (Criteria) this;
        }

        public Criteria andF_licenceaddressNotBetween(String value1, String value2) {
            addCriterion("f_licenceaddress not between", value1, value2, "f_licenceaddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bd_orderform
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 21 15:40:14 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bd_orderform
     *
     * @mbggenerated Wed Oct 21 15:40:14 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}