package com.etong.pt.data.cmvehicle;

import com.etong.pt.data.cmvehicle.CmVehicle;
import com.etong.pt.data.cmvehicle.CmVehicleExample;
import com.etong.pt.data.cmvehicle.CmVehicleWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    int countByExample(CmVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    int deleteByExample(CmVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    int deleteByPrimaryKey(Short f_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    int insert(CmVehicleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    int insertSelective(CmVehicleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    List<CmVehicleWithBLOBs> selectByExampleWithBLOBs(CmVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    List<CmVehicle> selectByExample(CmVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    CmVehicleWithBLOBs selectByPrimaryKey(Short f_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") CmVehicleWithBLOBs record, @Param("example") CmVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") CmVehicleWithBLOBs record, @Param("example") CmVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    int updateByExample(@Param("record") CmVehicle record, @Param("example") CmVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    int updateByPrimaryKeySelective(CmVehicleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(CmVehicleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    int updateByPrimaryKey(CmVehicle record);
}