package com.etong.pt.data.cmvehicle;

public class CmVehicleWithBLOBs extends CmVehicle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_impression
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_impression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_merit
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_merit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_weakness
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_weakness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_appearance
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_appearance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_interior
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_interior;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_space
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_space;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_Handling
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_Handling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_power
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_fuel
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_fuel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_assembly
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_assembly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_cust_serv
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_cust_serv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_safe
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_safe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_other
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_other;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_summary
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_brand_desc
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_brand_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle.f_description
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    private String f_description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_impression
     *
     * @return the value of t_cm_vehicle.f_impression
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_impression() {
        return f_impression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_impression
     *
     * @param f_impression the value for t_cm_vehicle.f_impression
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_impression(String f_impression) {
        this.f_impression = f_impression == null ? null : f_impression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_merit
     *
     * @return the value of t_cm_vehicle.f_merit
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_merit() {
        return f_merit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_merit
     *
     * @param f_merit the value for t_cm_vehicle.f_merit
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_merit(String f_merit) {
        this.f_merit = f_merit == null ? null : f_merit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_weakness
     *
     * @return the value of t_cm_vehicle.f_weakness
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_weakness() {
        return f_weakness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_weakness
     *
     * @param f_weakness the value for t_cm_vehicle.f_weakness
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_weakness(String f_weakness) {
        this.f_weakness = f_weakness == null ? null : f_weakness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_appearance
     *
     * @return the value of t_cm_vehicle.f_appearance
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_appearance() {
        return f_appearance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_appearance
     *
     * @param f_appearance the value for t_cm_vehicle.f_appearance
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_appearance(String f_appearance) {
        this.f_appearance = f_appearance == null ? null : f_appearance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_interior
     *
     * @return the value of t_cm_vehicle.f_interior
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_interior() {
        return f_interior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_interior
     *
     * @param f_interior the value for t_cm_vehicle.f_interior
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_interior(String f_interior) {
        this.f_interior = f_interior == null ? null : f_interior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_space
     *
     * @return the value of t_cm_vehicle.f_space
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_space() {
        return f_space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_space
     *
     * @param f_space the value for t_cm_vehicle.f_space
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_space(String f_space) {
        this.f_space = f_space == null ? null : f_space.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_Handling
     *
     * @return the value of t_cm_vehicle.f_Handling
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_Handling() {
        return f_Handling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_Handling
     *
     * @param f_Handling the value for t_cm_vehicle.f_Handling
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_Handling(String f_Handling) {
        this.f_Handling = f_Handling == null ? null : f_Handling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_power
     *
     * @return the value of t_cm_vehicle.f_power
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_power() {
        return f_power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_power
     *
     * @param f_power the value for t_cm_vehicle.f_power
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_power(String f_power) {
        this.f_power = f_power == null ? null : f_power.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_fuel
     *
     * @return the value of t_cm_vehicle.f_fuel
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_fuel() {
        return f_fuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_fuel
     *
     * @param f_fuel the value for t_cm_vehicle.f_fuel
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_fuel(String f_fuel) {
        this.f_fuel = f_fuel == null ? null : f_fuel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_assembly
     *
     * @return the value of t_cm_vehicle.f_assembly
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_assembly() {
        return f_assembly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_assembly
     *
     * @param f_assembly the value for t_cm_vehicle.f_assembly
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_assembly(String f_assembly) {
        this.f_assembly = f_assembly == null ? null : f_assembly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_cust_serv
     *
     * @return the value of t_cm_vehicle.f_cust_serv
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_cust_serv() {
        return f_cust_serv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_cust_serv
     *
     * @param f_cust_serv the value for t_cm_vehicle.f_cust_serv
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_cust_serv(String f_cust_serv) {
        this.f_cust_serv = f_cust_serv == null ? null : f_cust_serv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_safe
     *
     * @return the value of t_cm_vehicle.f_safe
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_safe() {
        return f_safe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_safe
     *
     * @param f_safe the value for t_cm_vehicle.f_safe
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_safe(String f_safe) {
        this.f_safe = f_safe == null ? null : f_safe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_other
     *
     * @return the value of t_cm_vehicle.f_other
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_other() {
        return f_other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_other
     *
     * @param f_other the value for t_cm_vehicle.f_other
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_other(String f_other) {
        this.f_other = f_other == null ? null : f_other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_summary
     *
     * @return the value of t_cm_vehicle.f_summary
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_summary() {
        return f_summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_summary
     *
     * @param f_summary the value for t_cm_vehicle.f_summary
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_summary(String f_summary) {
        this.f_summary = f_summary == null ? null : f_summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_brand_desc
     *
     * @return the value of t_cm_vehicle.f_brand_desc
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_brand_desc() {
        return f_brand_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_brand_desc
     *
     * @param f_brand_desc the value for t_cm_vehicle.f_brand_desc
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_brand_desc(String f_brand_desc) {
        this.f_brand_desc = f_brand_desc == null ? null : f_brand_desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle.f_description
     *
     * @return the value of t_cm_vehicle.f_description
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public String getF_description() {
        return f_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle.f_description
     *
     * @param f_description the value for t_cm_vehicle.f_description
     *
     * @mbggenerated Wed Oct 28 17:31:14 CST 2015
     */
    public void setF_description(String f_description) {
        this.f_description = f_description == null ? null : f_description.trim();
    }
}