package com.etong.pt.data.sysitem;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    int countByExample(SysItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    int deleteByExample(SysItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    int deleteByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    int insert(SysItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    int insertSelective(SysItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    List<SysItem> selectByExampleWithBLOBs(SysItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    List<SysItem> selectByExample(SysItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    SysItem selectByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysItem record, @Param("example") SysItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") SysItem record, @Param("example") SysItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    int updateByExample(@Param("record") SysItem record, @Param("example") SysItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    int updateByPrimaryKeySelective(SysItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(SysItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_item
     *
     * @mbggenerated Wed Nov 25 17:04:16 CST 2015
     */
    int updateByPrimaryKey(SysItem record);
}