package com.etong.pt.data.activities;

import java.io.Serializable;

public class Activities implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_activities.f_acid
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    private Long acid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_activities.f_title
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_activities.f_startdate
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    private Integer startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_activities.f_enddate
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    private Integer enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_activities.f_type
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_activities.f_stid
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    private String stid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_activities.f_image
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_activities.f_content
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_activities.f_acid
     *
     * @return the value of t_bd_activities.f_acid
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public Long getAcid() {
        return acid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_activities.f_acid
     *
     * @param acid the value for t_bd_activities.f_acid
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public void setAcid(Long acid) {
        this.acid = acid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_activities.f_title
     *
     * @return the value of t_bd_activities.f_title
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_activities.f_title
     *
     * @param title the value for t_bd_activities.f_title
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_activities.f_startdate
     *
     * @return the value of t_bd_activities.f_startdate
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public Integer getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_activities.f_startdate
     *
     * @param startdate the value for t_bd_activities.f_startdate
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public void setStartdate(Integer startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_activities.f_enddate
     *
     * @return the value of t_bd_activities.f_enddate
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public Integer getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_activities.f_enddate
     *
     * @param enddate the value for t_bd_activities.f_enddate
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public void setEnddate(Integer enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_activities.f_type
     *
     * @return the value of t_bd_activities.f_type
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_activities.f_type
     *
     * @param type the value for t_bd_activities.f_type
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_activities.f_stid
     *
     * @return the value of t_bd_activities.f_stid
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public String getStid() {
        return stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_activities.f_stid
     *
     * @param stid the value for t_bd_activities.f_stid
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public void setStid(String stid) {
        this.stid = stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_activities.f_image
     *
     * @return the value of t_bd_activities.f_image
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_activities.f_image
     *
     * @param image the value for t_bd_activities.f_image
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_activities.f_content
     *
     * @return the value of t_bd_activities.f_content
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_activities.f_content
     *
     * @param content the value for t_bd_activities.f_content
     *
     * @mbggenerated Tue Dec 01 13:44:14 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }
}