package com.etong.pt.data.app;

import java.io.Serializable;

public class App implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_system.f_stid
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    private String f_stid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_system.f_stname
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    private String f_stname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_system.f_pstid
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    private String f_pstid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_system.f_accredit
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    private String f_accredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_system.f_url
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    private String f_url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_system.f_stid
     *
     * @return the value of t_pm_system.f_stid
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    public String getF_stid() {
        return f_stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_system.f_stid
     *
     * @param f_stid the value for t_pm_system.f_stid
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    public void setF_stid(String f_stid) {
        this.f_stid = f_stid == null ? null : f_stid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_system.f_stname
     *
     * @return the value of t_pm_system.f_stname
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    public String getF_stname() {
        return f_stname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_system.f_stname
     *
     * @param f_stname the value for t_pm_system.f_stname
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    public void setF_stname(String f_stname) {
        this.f_stname = f_stname == null ? null : f_stname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_system.f_pstid
     *
     * @return the value of t_pm_system.f_pstid
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    public String getF_pstid() {
        return f_pstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_system.f_pstid
     *
     * @param f_pstid the value for t_pm_system.f_pstid
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    public void setF_pstid(String f_pstid) {
        this.f_pstid = f_pstid == null ? null : f_pstid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_system.f_accredit
     *
     * @return the value of t_pm_system.f_accredit
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    public String getF_accredit() {
        return f_accredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_system.f_accredit
     *
     * @param f_accredit the value for t_pm_system.f_accredit
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    public void setF_accredit(String f_accredit) {
        this.f_accredit = f_accredit == null ? null : f_accredit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_system.f_url
     *
     * @return the value of t_pm_system.f_url
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    public String getF_url() {
        return f_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_system.f_url
     *
     * @param f_url the value for t_pm_system.f_url
     *
     * @mbggenerated Mon Oct 19 15:04:31 CST 2015
     */
    public void setF_url(String f_url) {
        this.f_url = f_url == null ? null : f_url.trim();
    }
}