package com.etong.pt.data.bargain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class BargainInfoExample {
    private Integer start;
    private Integer limit;

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public BargainInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andF_bgidIsNull() {
            addCriterion("f_bgid is null");
            return (Criteria) this;
        }

        public Criteria andF_bgidIsNotNull() {
            addCriterion("f_bgid is not null");
            return (Criteria) this;
        }

        public Criteria andF_bgidEqualTo(Long value) {
            addCriterion("f_bgid =", value, "f_bgid");
            return (Criteria) this;
        }

        public Criteria andF_bgidNotEqualTo(Long value) {
            addCriterion("f_bgid <>", value, "f_bgid");
            return (Criteria) this;
        }

        public Criteria andF_bgidGreaterThan(Long value) {
            addCriterion("f_bgid >", value, "f_bgid");
            return (Criteria) this;
        }

        public Criteria andF_bgidGreaterThanOrEqualTo(Long value) {
            addCriterion("f_bgid >=", value, "f_bgid");
            return (Criteria) this;
        }

        public Criteria andF_bgidLessThan(Long value) {
            addCriterion("f_bgid <", value, "f_bgid");
            return (Criteria) this;
        }

        public Criteria andF_bgidLessThanOrEqualTo(Long value) {
            addCriterion("f_bgid <=", value, "f_bgid");
            return (Criteria) this;
        }

        public Criteria andF_bgidIn(List<Long> values) {
            addCriterion("f_bgid in", values, "f_bgid");
            return (Criteria) this;
        }

        public Criteria andF_bgidNotIn(List<Long> values) {
            addCriterion("f_bgid not in", values, "f_bgid");
            return (Criteria) this;
        }

        public Criteria andF_bgidBetween(Long value1, Long value2) {
            addCriterion("f_bgid between", value1, value2, "f_bgid");
            return (Criteria) this;
        }

        public Criteria andF_bgidNotBetween(Long value1, Long value2) {
            addCriterion("f_bgid not between", value1, value2, "f_bgid");
            return (Criteria) this;
        }

        public Criteria andF_ofidIsNull() {
            addCriterion("f_ofid is null");
            return (Criteria) this;
        }

        public Criteria andF_ofidIsNotNull() {
            addCriterion("f_ofid is not null");
            return (Criteria) this;
        }

        public Criteria andF_ofidEqualTo(Long value) {
            addCriterion("f_ofid =", value, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidNotEqualTo(Long value) {
            addCriterion("f_ofid <>", value, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidGreaterThan(Long value) {
            addCriterion("f_ofid >", value, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidGreaterThanOrEqualTo(Long value) {
            addCriterion("f_ofid >=", value, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidLessThan(Long value) {
            addCriterion("f_ofid <", value, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidLessThanOrEqualTo(Long value) {
            addCriterion("f_ofid <=", value, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidIn(List<Long> values) {
            addCriterion("f_ofid in", values, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidNotIn(List<Long> values) {
            addCriterion("f_ofid not in", values, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidBetween(Long value1, Long value2) {
            addCriterion("f_ofid between", value1, value2, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofidNotBetween(Long value1, Long value2) {
            addCriterion("f_ofid not between", value1, value2, "f_ofid");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeIsNull() {
            addCriterion("f_ofcode is null");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeIsNotNull() {
            addCriterion("f_ofcode is not null");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeEqualTo(String value) {
            addCriterion("f_ofcode =", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeNotEqualTo(String value) {
            addCriterion("f_ofcode <>", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeGreaterThan(String value) {
            addCriterion("f_ofcode >", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeGreaterThanOrEqualTo(String value) {
            addCriterion("f_ofcode >=", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeLessThan(String value) {
            addCriterion("f_ofcode <", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeLessThanOrEqualTo(String value) {
            addCriterion("f_ofcode <=", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeLike(String value) {
            addCriterion("f_ofcode like", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeNotLike(String value) {
            addCriterion("f_ofcode not like", value, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeIn(List<String> values) {
            addCriterion("f_ofcode in", values, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeNotIn(List<String> values) {
            addCriterion("f_ofcode not in", values, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeBetween(String value1, String value2) {
            addCriterion("f_ofcode between", value1, value2, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_ofcodeNotBetween(String value1, String value2) {
            addCriterion("f_ofcode not between", value1, value2, "f_ofcode");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeIsNull() {
            addCriterion("f_devicecode is null");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeIsNotNull() {
            addCriterion("f_devicecode is not null");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeEqualTo(String value) {
            addCriterion("f_devicecode =", value, "f_devicecode");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeNotEqualTo(String value) {
            addCriterion("f_devicecode <>", value, "f_devicecode");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeGreaterThan(String value) {
            addCriterion("f_devicecode >", value, "f_devicecode");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeGreaterThanOrEqualTo(String value) {
            addCriterion("f_devicecode >=", value, "f_devicecode");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeLessThan(String value) {
            addCriterion("f_devicecode <", value, "f_devicecode");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeLessThanOrEqualTo(String value) {
            addCriterion("f_devicecode <=", value, "f_devicecode");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeLike(String value) {
            addCriterion("f_devicecode like", value, "f_devicecode");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeNotLike(String value) {
            addCriterion("f_devicecode not like", value, "f_devicecode");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeIn(List<String> values) {
            addCriterion("f_devicecode in", values, "f_devicecode");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeNotIn(List<String> values) {
            addCriterion("f_devicecode not in", values, "f_devicecode");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeBetween(String value1, String value2) {
            addCriterion("f_devicecode between", value1, value2, "f_devicecode");
            return (Criteria) this;
        }

        public Criteria andF_devicecodeNotBetween(String value1, String value2) {
            addCriterion("f_devicecode not between", value1, value2, "f_devicecode");
            return (Criteria) this;
        }

        public Criteria andF_derateIsNull() {
            addCriterion("f_derate is null");
            return (Criteria) this;
        }

        public Criteria andF_derateIsNotNull() {
            addCriterion("f_derate is not null");
            return (Criteria) this;
        }

        public Criteria andF_derateEqualTo(BigDecimal value) {
            addCriterion("f_derate =", value, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateNotEqualTo(BigDecimal value) {
            addCriterion("f_derate <>", value, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateGreaterThan(BigDecimal value) {
            addCriterion("f_derate >", value, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("f_derate >=", value, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateLessThan(BigDecimal value) {
            addCriterion("f_derate <", value, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("f_derate <=", value, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateIn(List<BigDecimal> values) {
            addCriterion("f_derate in", values, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateNotIn(List<BigDecimal> values) {
            addCriterion("f_derate not in", values, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("f_derate between", value1, value2, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_derateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("f_derate not between", value1, value2, "f_derate");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeIsNull() {
            addCriterion("f_operatetime is null");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeIsNotNull() {
            addCriterion("f_operatetime is not null");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeEqualTo(Integer value) {
            addCriterion("f_operatetime =", value, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeNotEqualTo(Integer value) {
            addCriterion("f_operatetime <>", value, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeGreaterThan(Integer value) {
            addCriterion("f_operatetime >", value, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_operatetime >=", value, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeLessThan(Integer value) {
            addCriterion("f_operatetime <", value, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeLessThanOrEqualTo(Integer value) {
            addCriterion("f_operatetime <=", value, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeIn(List<Integer> values) {
            addCriterion("f_operatetime in", values, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeNotIn(List<Integer> values) {
            addCriterion("f_operatetime not in", values, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeBetween(Integer value1, Integer value2) {
            addCriterion("f_operatetime between", value1, value2, "f_operatetime");
            return (Criteria) this;
        }

        public Criteria andF_operatetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("f_operatetime not between", value1, value2, "f_operatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bd_bargain
     *
     * @mbggenerated do_not_delete_during_merge Fri Oct 30 15:24:33 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}