package com.etong.pt.data.bargain;

import com.etong.pt.data.bargain.BargainInfo;
import com.etong.pt.data.bargain.BargainInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BargainInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    int countByExample(BargainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    int deleteByExample(BargainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    int deleteByPrimaryKey(Long f_bgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    int insert(BargainInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    int insertSelective(BargainInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    List<BargainInfo> selectByExample(BargainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    BargainInfo selectByPrimaryKey(Long f_bgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") BargainInfo record, @Param("example") BargainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    int updateByExample(@Param("record") BargainInfo record, @Param("example") BargainInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    int updateByPrimaryKeySelective(BargainInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_bargain
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    int updateByPrimaryKey(BargainInfo record);
}