package com.etong.pt.data.bargain;

import java.io.Serializable;
import java.math.BigDecimal;

public class BargainInfo implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_bargain.f_bgid
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    private Long f_bgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_bargain.f_ofid
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    private Long f_ofid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_bargain.f_ofcode
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    private String f_ofcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_bargain.f_devicecode
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    private String f_devicecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_bargain.f_derate
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    private BigDecimal f_derate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_bargain.f_operatetime
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    private Integer f_operatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_bargain.f_bgid
     *
     * @return the value of t_bd_bargain.f_bgid
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public Long getF_bgid() {
        return f_bgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_bargain.f_bgid
     *
     * @param f_bgid the value for t_bd_bargain.f_bgid
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public void setF_bgid(Long f_bgid) {
        this.f_bgid = f_bgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_bargain.f_ofid
     *
     * @return the value of t_bd_bargain.f_ofid
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public Long getF_ofid() {
        return f_ofid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_bargain.f_ofid
     *
     * @param f_ofid the value for t_bd_bargain.f_ofid
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public void setF_ofid(Long f_ofid) {
        this.f_ofid = f_ofid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_bargain.f_ofcode
     *
     * @return the value of t_bd_bargain.f_ofcode
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public String getF_ofcode() {
        return f_ofcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_bargain.f_ofcode
     *
     * @param f_ofcode the value for t_bd_bargain.f_ofcode
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public void setF_ofcode(String f_ofcode) {
        this.f_ofcode = f_ofcode == null ? null : f_ofcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_bargain.f_devicecode
     *
     * @return the value of t_bd_bargain.f_devicecode
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public String getF_devicecode() {
        return f_devicecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_bargain.f_devicecode
     *
     * @param f_devicecode the value for t_bd_bargain.f_devicecode
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public void setF_devicecode(String f_devicecode) {
        this.f_devicecode = f_devicecode == null ? null : f_devicecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_bargain.f_derate
     *
     * @return the value of t_bd_bargain.f_derate
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public BigDecimal getF_derate() {
        return f_derate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_bargain.f_derate
     *
     * @param f_derate the value for t_bd_bargain.f_derate
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public void setF_derate(BigDecimal f_derate) {
        this.f_derate = f_derate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_bargain.f_operatetime
     *
     * @return the value of t_bd_bargain.f_operatetime
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public Integer getF_operatetime() {
        return f_operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_bargain.f_operatetime
     *
     * @param f_operatetime the value for t_bd_bargain.f_operatetime
     *
     * @mbggenerated Fri Oct 30 15:24:33 CST 2015
     */
    public void setF_operatetime(Integer f_operatetime) {
        this.f_operatetime = f_operatetime;
    }
}