package com.etong.pt.data.salesvehicle;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SalesVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_salesvehicle
     *
     * @mbggenerated Tue Dec 01 14:05:28 CST 2015
     */
    int countByExample(SalesVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_salesvehicle
     *
     * @mbggenerated Tue Dec 01 14:05:28 CST 2015
     */
    int deleteByExample(SalesVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_salesvehicle
     *
     * @mbggenerated Tue Dec 01 14:05:28 CST 2015
     */
    int deleteByPrimaryKey(Integer svid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_salesvehicle
     *
     * @mbggenerated Tue Dec 01 14:05:28 CST 2015
     */
    int insert(SalesVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_salesvehicle
     *
     * @mbggenerated Tue Dec 01 14:05:28 CST 2015
     */
    int insertSelective(SalesVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_salesvehicle
     *
     * @mbggenerated Tue Dec 01 14:05:28 CST 2015
     */
    List<SalesVehicle> selectByExample(SalesVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_salesvehicle
     *
     * @mbggenerated Tue Dec 01 14:05:28 CST 2015
     */
    SalesVehicle selectByPrimaryKey(Integer svid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_salesvehicle
     *
     * @mbggenerated Tue Dec 01 14:05:28 CST 2015
     */
    int updateByExampleSelective(@Param("record") SalesVehicle record, @Param("example") SalesVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_salesvehicle
     *
     * @mbggenerated Tue Dec 01 14:05:28 CST 2015
     */
    int updateByExample(@Param("record") SalesVehicle record, @Param("example") SalesVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_salesvehicle
     *
     * @mbggenerated Tue Dec 01 14:05:28 CST 2015
     */
    int updateByPrimaryKeySelective(SalesVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_salesvehicle
     *
     * @mbggenerated Tue Dec 01 14:05:28 CST 2015
     */
    int updateByPrimaryKey(SalesVehicle record);
}