package com.etong.pt.data.carlever;

import java.io.Serializable;

public class CarLever implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_carlever.f_id
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    private Integer f_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_carlever.f_pid
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    private Integer f_pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_carlever.f_level
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    private Integer f_level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_carlever.f_title
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    private String f_title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_carlever.f_letter
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    private String f_letter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_carlever.f_vieworder
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    private Integer f_vieworder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_carlever.f_trueorder
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    private Integer f_trueorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_carlever.f_closed
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    private Boolean f_closed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_carlever.f_clicks
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    private Integer f_clicks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_carlever.f_archives
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    private Integer f_archives;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_carlever.f_keywords
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    private String f_keywords;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_carlever.f_id
     *
     * @return the value of t_cm_carlever.f_id
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public Integer getF_id() {
        return f_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_carlever.f_id
     *
     * @param f_id the value for t_cm_carlever.f_id
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void setF_id(Integer f_id) {
        this.f_id = f_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_carlever.f_pid
     *
     * @return the value of t_cm_carlever.f_pid
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public Integer getF_pid() {
        return f_pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_carlever.f_pid
     *
     * @param f_pid the value for t_cm_carlever.f_pid
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void setF_pid(Integer f_pid) {
        this.f_pid = f_pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_carlever.f_level
     *
     * @return the value of t_cm_carlever.f_level
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public Integer getF_level() {
        return f_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_carlever.f_level
     *
     * @param f_level the value for t_cm_carlever.f_level
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void setF_level(Integer f_level) {
        this.f_level = f_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_carlever.f_title
     *
     * @return the value of t_cm_carlever.f_title
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public String getF_title() {
        return f_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_carlever.f_title
     *
     * @param f_title the value for t_cm_carlever.f_title
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void setF_title(String f_title) {
        this.f_title = f_title == null ? null : f_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_carlever.f_letter
     *
     * @return the value of t_cm_carlever.f_letter
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public String getF_letter() {
        return f_letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_carlever.f_letter
     *
     * @param f_letter the value for t_cm_carlever.f_letter
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void setF_letter(String f_letter) {
        this.f_letter = f_letter == null ? null : f_letter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_carlever.f_vieworder
     *
     * @return the value of t_cm_carlever.f_vieworder
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public Integer getF_vieworder() {
        return f_vieworder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_carlever.f_vieworder
     *
     * @param f_vieworder the value for t_cm_carlever.f_vieworder
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void setF_vieworder(Integer f_vieworder) {
        this.f_vieworder = f_vieworder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_carlever.f_trueorder
     *
     * @return the value of t_cm_carlever.f_trueorder
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public Integer getF_trueorder() {
        return f_trueorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_carlever.f_trueorder
     *
     * @param f_trueorder the value for t_cm_carlever.f_trueorder
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void setF_trueorder(Integer f_trueorder) {
        this.f_trueorder = f_trueorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_carlever.f_closed
     *
     * @return the value of t_cm_carlever.f_closed
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public Boolean getF_closed() {
        return f_closed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_carlever.f_closed
     *
     * @param f_closed the value for t_cm_carlever.f_closed
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void setF_closed(Boolean f_closed) {
        this.f_closed = f_closed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_carlever.f_clicks
     *
     * @return the value of t_cm_carlever.f_clicks
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public Integer getF_clicks() {
        return f_clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_carlever.f_clicks
     *
     * @param f_clicks the value for t_cm_carlever.f_clicks
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void setF_clicks(Integer f_clicks) {
        this.f_clicks = f_clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_carlever.f_archives
     *
     * @return the value of t_cm_carlever.f_archives
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public Integer getF_archives() {
        return f_archives;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_carlever.f_archives
     *
     * @param f_archives the value for t_cm_carlever.f_archives
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void setF_archives(Integer f_archives) {
        this.f_archives = f_archives;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_carlever.f_keywords
     *
     * @return the value of t_cm_carlever.f_keywords
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public String getF_keywords() {
        return f_keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_carlever.f_keywords
     *
     * @param f_keywords the value for t_cm_carlever.f_keywords
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void setF_keywords(String f_keywords) {
        this.f_keywords = f_keywords == null ? null : f_keywords.trim();
    }
}