package com.etong.pt.data.carlever;

import com.etong.pt.data.carlever.CarLever;
import com.etong.pt.data.carlever.CarLeverExample;
import com.etong.pt.data.carlever.CarLeverWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarLeverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    int countByExample(CarLeverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    int deleteByExample(CarLeverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    int deleteByPrimaryKey(Short f_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    int insert(CarLeverWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    int insertSelective(CarLeverWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    List<CarLeverWithBLOBs> selectByExampleWithBLOBs(CarLeverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    List<CarLever> selectByExample(CarLeverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    CarLeverWithBLOBs selectByPrimaryKey(Short f_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    int updateByExampleSelective(@Param("record") CarLeverWithBLOBs record, @Param("example") CarLeverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") CarLeverWithBLOBs record, @Param("example") CarLeverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    int updateByExample(@Param("record") CarLever record, @Param("example") CarLeverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    int updateByPrimaryKeySelective(CarLeverWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(CarLeverWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    int updateByPrimaryKey(CarLever record);
}