package com.etong.pt.data.carlever;

import java.util.ArrayList;
import java.util.List;

public class CarLeverExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public CarLeverExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andF_idIsNull() {
            addCriterion("f_id is null");
            return (Criteria) this;
        }

        public Criteria andF_idIsNotNull() {
            addCriterion("f_id is not null");
            return (Criteria) this;
        }

        public Criteria andF_idEqualTo(Integer value) {
            addCriterion("f_id =", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotEqualTo(Integer value) {
            addCriterion("f_id <>", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idGreaterThan(Integer value) {
            addCriterion("f_id >", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_id >=", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idLessThan(Integer value) {
            addCriterion("f_id <", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idLessThanOrEqualTo(Integer value) {
            addCriterion("f_id <=", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idIn(List<Integer> values) {
            addCriterion("f_id in", values, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotIn(List<Integer> values) {
            addCriterion("f_id not in", values, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idBetween(Integer value1, Integer value2) {
            addCriterion("f_id between", value1, value2, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotBetween(Integer value1, Integer value2) {
            addCriterion("f_id not between", value1, value2, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_pidIsNull() {
            addCriterion("f_pid is null");
            return (Criteria) this;
        }

        public Criteria andF_pidIsNotNull() {
            addCriterion("f_pid is not null");
            return (Criteria) this;
        }

        public Criteria andF_pidEqualTo(Integer value) {
            addCriterion("f_pid =", value, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidNotEqualTo(Integer value) {
            addCriterion("f_pid <>", value, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidGreaterThan(Integer value) {
            addCriterion("f_pid >", value, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_pid >=", value, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidLessThan(Integer value) {
            addCriterion("f_pid <", value, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidLessThanOrEqualTo(Integer value) {
            addCriterion("f_pid <=", value, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidIn(List<Integer> values) {
            addCriterion("f_pid in", values, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidNotIn(List<Integer> values) {
            addCriterion("f_pid not in", values, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidBetween(Integer value1, Integer value2) {
            addCriterion("f_pid between", value1, value2, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidNotBetween(Integer value1, Integer value2) {
            addCriterion("f_pid not between", value1, value2, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_levelIsNull() {
            addCriterion("f_level is null");
            return (Criteria) this;
        }

        public Criteria andF_levelIsNotNull() {
            addCriterion("f_level is not null");
            return (Criteria) this;
        }

        public Criteria andF_levelEqualTo(Integer value) {
            addCriterion("f_level =", value, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelNotEqualTo(Integer value) {
            addCriterion("f_level <>", value, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelGreaterThan(Integer value) {
            addCriterion("f_level >", value, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_level >=", value, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelLessThan(Integer value) {
            addCriterion("f_level <", value, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelLessThanOrEqualTo(Integer value) {
            addCriterion("f_level <=", value, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelIn(List<Integer> values) {
            addCriterion("f_level in", values, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelNotIn(List<Integer> values) {
            addCriterion("f_level not in", values, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelBetween(Integer value1, Integer value2) {
            addCriterion("f_level between", value1, value2, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelNotBetween(Integer value1, Integer value2) {
            addCriterion("f_level not between", value1, value2, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_titleIsNull() {
            addCriterion("f_title is null");
            return (Criteria) this;
        }

        public Criteria andF_titleIsNotNull() {
            addCriterion("f_title is not null");
            return (Criteria) this;
        }

        public Criteria andF_titleEqualTo(String value) {
            addCriterion("f_title =", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleNotEqualTo(String value) {
            addCriterion("f_title <>", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleGreaterThan(String value) {
            addCriterion("f_title >", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleGreaterThanOrEqualTo(String value) {
            addCriterion("f_title >=", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleLessThan(String value) {
            addCriterion("f_title <", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleLessThanOrEqualTo(String value) {
            addCriterion("f_title <=", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleLike(String value) {
            addCriterion("f_title like", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleNotLike(String value) {
            addCriterion("f_title not like", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleIn(List<String> values) {
            addCriterion("f_title in", values, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleNotIn(List<String> values) {
            addCriterion("f_title not in", values, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleBetween(String value1, String value2) {
            addCriterion("f_title between", value1, value2, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleNotBetween(String value1, String value2) {
            addCriterion("f_title not between", value1, value2, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_letterIsNull() {
            addCriterion("f_letter is null");
            return (Criteria) this;
        }

        public Criteria andF_letterIsNotNull() {
            addCriterion("f_letter is not null");
            return (Criteria) this;
        }

        public Criteria andF_letterEqualTo(String value) {
            addCriterion("f_letter =", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterNotEqualTo(String value) {
            addCriterion("f_letter <>", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterGreaterThan(String value) {
            addCriterion("f_letter >", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterGreaterThanOrEqualTo(String value) {
            addCriterion("f_letter >=", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterLessThan(String value) {
            addCriterion("f_letter <", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterLessThanOrEqualTo(String value) {
            addCriterion("f_letter <=", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterLike(String value) {
            addCriterion("f_letter like", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterNotLike(String value) {
            addCriterion("f_letter not like", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterIn(List<String> values) {
            addCriterion("f_letter in", values, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterNotIn(List<String> values) {
            addCriterion("f_letter not in", values, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterBetween(String value1, String value2) {
            addCriterion("f_letter between", value1, value2, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterNotBetween(String value1, String value2) {
            addCriterion("f_letter not between", value1, value2, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_vieworderIsNull() {
            addCriterion("f_vieworder is null");
            return (Criteria) this;
        }

        public Criteria andF_vieworderIsNotNull() {
            addCriterion("f_vieworder is not null");
            return (Criteria) this;
        }

        public Criteria andF_vieworderEqualTo(Integer value) {
            addCriterion("f_vieworder =", value, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderNotEqualTo(Integer value) {
            addCriterion("f_vieworder <>", value, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderGreaterThan(Integer value) {
            addCriterion("f_vieworder >", value, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_vieworder >=", value, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderLessThan(Integer value) {
            addCriterion("f_vieworder <", value, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderLessThanOrEqualTo(Integer value) {
            addCriterion("f_vieworder <=", value, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderIn(List<Integer> values) {
            addCriterion("f_vieworder in", values, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderNotIn(List<Integer> values) {
            addCriterion("f_vieworder not in", values, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderBetween(Integer value1, Integer value2) {
            addCriterion("f_vieworder between", value1, value2, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderNotBetween(Integer value1, Integer value2) {
            addCriterion("f_vieworder not between", value1, value2, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_trueorderIsNull() {
            addCriterion("f_trueorder is null");
            return (Criteria) this;
        }

        public Criteria andF_trueorderIsNotNull() {
            addCriterion("f_trueorder is not null");
            return (Criteria) this;
        }

        public Criteria andF_trueorderEqualTo(Integer value) {
            addCriterion("f_trueorder =", value, "f_trueorder");
            return (Criteria) this;
        }

        public Criteria andF_trueorderNotEqualTo(Integer value) {
            addCriterion("f_trueorder <>", value, "f_trueorder");
            return (Criteria) this;
        }

        public Criteria andF_trueorderGreaterThan(Integer value) {
            addCriterion("f_trueorder >", value, "f_trueorder");
            return (Criteria) this;
        }

        public Criteria andF_trueorderGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_trueorder >=", value, "f_trueorder");
            return (Criteria) this;
        }

        public Criteria andF_trueorderLessThan(Integer value) {
            addCriterion("f_trueorder <", value, "f_trueorder");
            return (Criteria) this;
        }

        public Criteria andF_trueorderLessThanOrEqualTo(Integer value) {
            addCriterion("f_trueorder <=", value, "f_trueorder");
            return (Criteria) this;
        }

        public Criteria andF_trueorderIn(List<Integer> values) {
            addCriterion("f_trueorder in", values, "f_trueorder");
            return (Criteria) this;
        }

        public Criteria andF_trueorderNotIn(List<Integer> values) {
            addCriterion("f_trueorder not in", values, "f_trueorder");
            return (Criteria) this;
        }

        public Criteria andF_trueorderBetween(Integer value1, Integer value2) {
            addCriterion("f_trueorder between", value1, value2, "f_trueorder");
            return (Criteria) this;
        }

        public Criteria andF_trueorderNotBetween(Integer value1, Integer value2) {
            addCriterion("f_trueorder not between", value1, value2, "f_trueorder");
            return (Criteria) this;
        }

        public Criteria andF_closedIsNull() {
            addCriterion("f_closed is null");
            return (Criteria) this;
        }

        public Criteria andF_closedIsNotNull() {
            addCriterion("f_closed is not null");
            return (Criteria) this;
        }

        public Criteria andF_closedEqualTo(Boolean value) {
            addCriterion("f_closed =", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedNotEqualTo(Boolean value) {
            addCriterion("f_closed <>", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedGreaterThan(Boolean value) {
            addCriterion("f_closed >", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("f_closed >=", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedLessThan(Boolean value) {
            addCriterion("f_closed <", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedLessThanOrEqualTo(Boolean value) {
            addCriterion("f_closed <=", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedIn(List<Boolean> values) {
            addCriterion("f_closed in", values, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedNotIn(List<Boolean> values) {
            addCriterion("f_closed not in", values, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedBetween(Boolean value1, Boolean value2) {
            addCriterion("f_closed between", value1, value2, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("f_closed not between", value1, value2, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_clicksIsNull() {
            addCriterion("f_clicks is null");
            return (Criteria) this;
        }

        public Criteria andF_clicksIsNotNull() {
            addCriterion("f_clicks is not null");
            return (Criteria) this;
        }

        public Criteria andF_clicksEqualTo(Integer value) {
            addCriterion("f_clicks =", value, "f_clicks");
            return (Criteria) this;
        }

        public Criteria andF_clicksNotEqualTo(Integer value) {
            addCriterion("f_clicks <>", value, "f_clicks");
            return (Criteria) this;
        }

        public Criteria andF_clicksGreaterThan(Integer value) {
            addCriterion("f_clicks >", value, "f_clicks");
            return (Criteria) this;
        }

        public Criteria andF_clicksGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_clicks >=", value, "f_clicks");
            return (Criteria) this;
        }

        public Criteria andF_clicksLessThan(Integer value) {
            addCriterion("f_clicks <", value, "f_clicks");
            return (Criteria) this;
        }

        public Criteria andF_clicksLessThanOrEqualTo(Integer value) {
            addCriterion("f_clicks <=", value, "f_clicks");
            return (Criteria) this;
        }

        public Criteria andF_clicksIn(List<Integer> values) {
            addCriterion("f_clicks in", values, "f_clicks");
            return (Criteria) this;
        }

        public Criteria andF_clicksNotIn(List<Integer> values) {
            addCriterion("f_clicks not in", values, "f_clicks");
            return (Criteria) this;
        }

        public Criteria andF_clicksBetween(Integer value1, Integer value2) {
            addCriterion("f_clicks between", value1, value2, "f_clicks");
            return (Criteria) this;
        }

        public Criteria andF_clicksNotBetween(Integer value1, Integer value2) {
            addCriterion("f_clicks not between", value1, value2, "f_clicks");
            return (Criteria) this;
        }

        public Criteria andF_archivesIsNull() {
            addCriterion("f_archives is null");
            return (Criteria) this;
        }

        public Criteria andF_archivesIsNotNull() {
            addCriterion("f_archives is not null");
            return (Criteria) this;
        }

        public Criteria andF_archivesEqualTo(Integer value) {
            addCriterion("f_archives =", value, "f_archives");
            return (Criteria) this;
        }

        public Criteria andF_archivesNotEqualTo(Integer value) {
            addCriterion("f_archives <>", value, "f_archives");
            return (Criteria) this;
        }

        public Criteria andF_archivesGreaterThan(Integer value) {
            addCriterion("f_archives >", value, "f_archives");
            return (Criteria) this;
        }

        public Criteria andF_archivesGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_archives >=", value, "f_archives");
            return (Criteria) this;
        }

        public Criteria andF_archivesLessThan(Integer value) {
            addCriterion("f_archives <", value, "f_archives");
            return (Criteria) this;
        }

        public Criteria andF_archivesLessThanOrEqualTo(Integer value) {
            addCriterion("f_archives <=", value, "f_archives");
            return (Criteria) this;
        }

        public Criteria andF_archivesIn(List<Integer> values) {
            addCriterion("f_archives in", values, "f_archives");
            return (Criteria) this;
        }

        public Criteria andF_archivesNotIn(List<Integer> values) {
            addCriterion("f_archives not in", values, "f_archives");
            return (Criteria) this;
        }

        public Criteria andF_archivesBetween(Integer value1, Integer value2) {
            addCriterion("f_archives between", value1, value2, "f_archives");
            return (Criteria) this;
        }

        public Criteria andF_archivesNotBetween(Integer value1, Integer value2) {
            addCriterion("f_archives not between", value1, value2, "f_archives");
            return (Criteria) this;
        }

        public Criteria andF_keywordsIsNull() {
            addCriterion("f_keywords is null");
            return (Criteria) this;
        }

        public Criteria andF_keywordsIsNotNull() {
            addCriterion("f_keywords is not null");
            return (Criteria) this;
        }

        public Criteria andF_keywordsEqualTo(String value) {
            addCriterion("f_keywords =", value, "f_keywords");
            return (Criteria) this;
        }

        public Criteria andF_keywordsNotEqualTo(String value) {
            addCriterion("f_keywords <>", value, "f_keywords");
            return (Criteria) this;
        }

        public Criteria andF_keywordsGreaterThan(String value) {
            addCriterion("f_keywords >", value, "f_keywords");
            return (Criteria) this;
        }

        public Criteria andF_keywordsGreaterThanOrEqualTo(String value) {
            addCriterion("f_keywords >=", value, "f_keywords");
            return (Criteria) this;
        }

        public Criteria andF_keywordsLessThan(String value) {
            addCriterion("f_keywords <", value, "f_keywords");
            return (Criteria) this;
        }

        public Criteria andF_keywordsLessThanOrEqualTo(String value) {
            addCriterion("f_keywords <=", value, "f_keywords");
            return (Criteria) this;
        }

        public Criteria andF_keywordsLike(String value) {
            addCriterion("f_keywords like", value, "f_keywords");
            return (Criteria) this;
        }

        public Criteria andF_keywordsNotLike(String value) {
            addCriterion("f_keywords not like", value, "f_keywords");
            return (Criteria) this;
        }

        public Criteria andF_keywordsIn(List<String> values) {
            addCriterion("f_keywords in", values, "f_keywords");
            return (Criteria) this;
        }

        public Criteria andF_keywordsNotIn(List<String> values) {
            addCriterion("f_keywords not in", values, "f_keywords");
            return (Criteria) this;
        }

        public Criteria andF_keywordsBetween(String value1, String value2) {
            addCriterion("f_keywords between", value1, value2, "f_keywords");
            return (Criteria) this;
        }

        public Criteria andF_keywordsNotBetween(String value1, String value2) {
            addCriterion("f_keywords not between", value1, value2, "f_keywords");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cm_carlever
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 28 17:30:28 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cm_carlever
     *
     * @mbggenerated Wed Oct 28 17:30:28 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}