package com.etong.pt.data.dealer;

import java.util.ArrayList;
import java.util.List;

public class DealerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	public DealerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andNcidIsNull() {
			addCriterion("f_ncid is null");
			return (Criteria) this;
		}

		public Criteria andNcidIsNotNull() {
			addCriterion("f_ncid is not null");
			return (Criteria) this;
		}

		public Criteria andNcidEqualTo(Integer value) {
			addCriterion("f_ncid =", value, "ncid");
			return (Criteria) this;
		}

		public Criteria andNcidNotEqualTo(Integer value) {
			addCriterion("f_ncid <>", value, "ncid");
			return (Criteria) this;
		}

		public Criteria andNcidGreaterThan(Integer value) {
			addCriterion("f_ncid >", value, "ncid");
			return (Criteria) this;
		}

		public Criteria andNcidGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_ncid >=", value, "ncid");
			return (Criteria) this;
		}

		public Criteria andNcidLessThan(Integer value) {
			addCriterion("f_ncid <", value, "ncid");
			return (Criteria) this;
		}

		public Criteria andNcidLessThanOrEqualTo(Integer value) {
			addCriterion("f_ncid <=", value, "ncid");
			return (Criteria) this;
		}

		public Criteria andNcidIn(List<Integer> values) {
			addCriterion("f_ncid in", values, "ncid");
			return (Criteria) this;
		}

		public Criteria andNcidNotIn(List<Integer> values) {
			addCriterion("f_ncid not in", values, "ncid");
			return (Criteria) this;
		}

		public Criteria andNcidBetween(Integer value1, Integer value2) {
			addCriterion("f_ncid between", value1, value2, "ncid");
			return (Criteria) this;
		}

		public Criteria andNcidNotBetween(Integer value1, Integer value2) {
			addCriterion("f_ncid not between", value1, value2, "ncid");
			return (Criteria) this;
		}

		public Criteria andTelIsNull() {
			addCriterion("f_tel is null");
			return (Criteria) this;
		}

		public Criteria andTelIsNotNull() {
			addCriterion("f_tel is not null");
			return (Criteria) this;
		}

		public Criteria andTelEqualTo(String value) {
			addCriterion("f_tel =", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotEqualTo(String value) {
			addCriterion("f_tel <>", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThan(String value) {
			addCriterion("f_tel >", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThanOrEqualTo(String value) {
			addCriterion("f_tel >=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThan(String value) {
			addCriterion("f_tel <", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThanOrEqualTo(String value) {
			addCriterion("f_tel <=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLike(String value) {
			addCriterion("f_tel like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotLike(String value) {
			addCriterion("f_tel not like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelIn(List<String> values) {
			addCriterion("f_tel in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotIn(List<String> values) {
			addCriterion("f_tel not in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelBetween(String value1, String value2) {
			addCriterion("f_tel between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotBetween(String value1, String value2) {
			addCriterion("f_tel not between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("f_phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("f_phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("f_phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("f_phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("f_phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("f_phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("f_phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("f_phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("f_phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("f_phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("f_phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("f_phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("f_phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("f_phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andFaxIsNull() {
			addCriterion("f_fax is null");
			return (Criteria) this;
		}

		public Criteria andFaxIsNotNull() {
			addCriterion("f_fax is not null");
			return (Criteria) this;
		}

		public Criteria andFaxEqualTo(String value) {
			addCriterion("f_fax =", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotEqualTo(String value) {
			addCriterion("f_fax <>", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxGreaterThan(String value) {
			addCriterion("f_fax >", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxGreaterThanOrEqualTo(String value) {
			addCriterion("f_fax >=", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLessThan(String value) {
			addCriterion("f_fax <", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLessThanOrEqualTo(String value) {
			addCriterion("f_fax <=", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLike(String value) {
			addCriterion("f_fax like", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotLike(String value) {
			addCriterion("f_fax not like", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxIn(List<String> values) {
			addCriterion("f_fax in", values, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotIn(List<String> values) {
			addCriterion("f_fax not in", values, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxBetween(String value1, String value2) {
			addCriterion("f_fax between", value1, value2, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotBetween(String value1, String value2) {
			addCriterion("f_fax not between", value1, value2, "fax");
			return (Criteria) this;
		}

		public Criteria andCompanyIsNull() {
			addCriterion("f_company is null");
			return (Criteria) this;
		}

		public Criteria andCompanyIsNotNull() {
			addCriterion("f_company is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyEqualTo(String value) {
			addCriterion("f_company =", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyNotEqualTo(String value) {
			addCriterion("f_company <>", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyGreaterThan(String value) {
			addCriterion("f_company >", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyGreaterThanOrEqualTo(String value) {
			addCriterion("f_company >=", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyLessThan(String value) {
			addCriterion("f_company <", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyLessThanOrEqualTo(String value) {
			addCriterion("f_company <=", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyLike(String value) {
			addCriterion("f_company like", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyNotLike(String value) {
			addCriterion("f_company not like", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyIn(List<String> values) {
			addCriterion("f_company in", values, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyNotIn(List<String> values) {
			addCriterion("f_company not in", values, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyBetween(String value1, String value2) {
			addCriterion("f_company between", value1, value2, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyNotBetween(String value1, String value2) {
			addCriterion("f_company not between", value1, value2, "company");
			return (Criteria) this;
		}

		public Criteria andLogoIsNull() {
			addCriterion("f_logo is null");
			return (Criteria) this;
		}

		public Criteria andLogoIsNotNull() {
			addCriterion("f_logo is not null");
			return (Criteria) this;
		}

		public Criteria andLogoEqualTo(String value) {
			addCriterion("f_logo =", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoNotEqualTo(String value) {
			addCriterion("f_logo <>", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoGreaterThan(String value) {
			addCriterion("f_logo >", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoGreaterThanOrEqualTo(String value) {
			addCriterion("f_logo >=", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoLessThan(String value) {
			addCriterion("f_logo <", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoLessThanOrEqualTo(String value) {
			addCriterion("f_logo <=", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoLike(String value) {
			addCriterion("f_logo like", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoNotLike(String value) {
			addCriterion("f_logo not like", value, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoIn(List<String> values) {
			addCriterion("f_logo in", values, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoNotIn(List<String> values) {
			addCriterion("f_logo not in", values, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoBetween(String value1, String value2) {
			addCriterion("f_logo between", value1, value2, "logo");
			return (Criteria) this;
		}

		public Criteria andLogoNotBetween(String value1, String value2) {
			addCriterion("f_logo not between", value1, value2, "logo");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("f_address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("f_address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("f_address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("f_address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("f_address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("f_address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("f_address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("f_address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("f_address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("f_address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("f_address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("f_address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("f_address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("f_address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andSitemapIsNull() {
			addCriterion("f_sitemap is null");
			return (Criteria) this;
		}

		public Criteria andSitemapIsNotNull() {
			addCriterion("f_sitemap is not null");
			return (Criteria) this;
		}

		public Criteria andSitemapEqualTo(String value) {
			addCriterion("f_sitemap =", value, "sitemap");
			return (Criteria) this;
		}

		public Criteria andSitemapNotEqualTo(String value) {
			addCriterion("f_sitemap <>", value, "sitemap");
			return (Criteria) this;
		}

		public Criteria andSitemapGreaterThan(String value) {
			addCriterion("f_sitemap >", value, "sitemap");
			return (Criteria) this;
		}

		public Criteria andSitemapGreaterThanOrEqualTo(String value) {
			addCriterion("f_sitemap >=", value, "sitemap");
			return (Criteria) this;
		}

		public Criteria andSitemapLessThan(String value) {
			addCriterion("f_sitemap <", value, "sitemap");
			return (Criteria) this;
		}

		public Criteria andSitemapLessThanOrEqualTo(String value) {
			addCriterion("f_sitemap <=", value, "sitemap");
			return (Criteria) this;
		}

		public Criteria andSitemapLike(String value) {
			addCriterion("f_sitemap like", value, "sitemap");
			return (Criteria) this;
		}

		public Criteria andSitemapNotLike(String value) {
			addCriterion("f_sitemap not like", value, "sitemap");
			return (Criteria) this;
		}

		public Criteria andSitemapIn(List<String> values) {
			addCriterion("f_sitemap in", values, "sitemap");
			return (Criteria) this;
		}

		public Criteria andSitemapNotIn(List<String> values) {
			addCriterion("f_sitemap not in", values, "sitemap");
			return (Criteria) this;
		}

		public Criteria andSitemapBetween(String value1, String value2) {
			addCriterion("f_sitemap between", value1, value2, "sitemap");
			return (Criteria) this;
		}

		public Criteria andSitemapNotBetween(String value1, String value2) {
			addCriterion("f_sitemap not between", value1, value2, "sitemap");
			return (Criteria) this;
		}

		public Criteria andLatitudeIsNull() {
			addCriterion("f_latitude is null");
			return (Criteria) this;
		}

		public Criteria andLatitudeIsNotNull() {
			addCriterion("f_latitude is not null");
			return (Criteria) this;
		}

		public Criteria andLatitudeEqualTo(Double value) {
			addCriterion("f_latitude =", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotEqualTo(Double value) {
			addCriterion("f_latitude <>", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeGreaterThan(Double value) {
			addCriterion("f_latitude >", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
			addCriterion("f_latitude >=", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeLessThan(Double value) {
			addCriterion("f_latitude <", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeLessThanOrEqualTo(Double value) {
			addCriterion("f_latitude <=", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeIn(List<Double> values) {
			addCriterion("f_latitude in", values, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotIn(List<Double> values) {
			addCriterion("f_latitude not in", values, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeBetween(Double value1, Double value2) {
			addCriterion("f_latitude between", value1, value2, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotBetween(Double value1, Double value2) {
			addCriterion("f_latitude not between", value1, value2, "latitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeIsNull() {
			addCriterion("f_longitude is null");
			return (Criteria) this;
		}

		public Criteria andLongitudeIsNotNull() {
			addCriterion("f_longitude is not null");
			return (Criteria) this;
		}

		public Criteria andLongitudeEqualTo(Double value) {
			addCriterion("f_longitude =", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotEqualTo(Double value) {
			addCriterion("f_longitude <>", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeGreaterThan(Double value) {
			addCriterion("f_longitude >", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
			addCriterion("f_longitude >=", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeLessThan(Double value) {
			addCriterion("f_longitude <", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeLessThanOrEqualTo(Double value) {
			addCriterion("f_longitude <=", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeIn(List<Double> values) {
			addCriterion("f_longitude in", values, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotIn(List<Double> values) {
			addCriterion("f_longitude not in", values, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeBetween(Double value1, Double value2) {
			addCriterion("f_longitude between", value1, value2, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotBetween(Double value1, Double value2) {
			addCriterion("f_longitude not between", value1, value2, "longitude");
			return (Criteria) this;
		}

		public Criteria andMainbrandIsNull() {
			addCriterion("f_mainbrand is null");
			return (Criteria) this;
		}

		public Criteria andMainbrandIsNotNull() {
			addCriterion("f_mainbrand is not null");
			return (Criteria) this;
		}

		public Criteria andMainbrandEqualTo(String value) {
			addCriterion("f_mainbrand =", value, "mainbrand");
			return (Criteria) this;
		}

		public Criteria andMainbrandNotEqualTo(String value) {
			addCriterion("f_mainbrand <>", value, "mainbrand");
			return (Criteria) this;
		}

		public Criteria andMainbrandGreaterThan(String value) {
			addCriterion("f_mainbrand >", value, "mainbrand");
			return (Criteria) this;
		}

		public Criteria andMainbrandGreaterThanOrEqualTo(String value) {
			addCriterion("f_mainbrand >=", value, "mainbrand");
			return (Criteria) this;
		}

		public Criteria andMainbrandLessThan(String value) {
			addCriterion("f_mainbrand <", value, "mainbrand");
			return (Criteria) this;
		}

		public Criteria andMainbrandLessThanOrEqualTo(String value) {
			addCriterion("f_mainbrand <=", value, "mainbrand");
			return (Criteria) this;
		}

		public Criteria andMainbrandLike(String value) {
			addCriterion("f_mainbrand like", value, "mainbrand");
			return (Criteria) this;
		}

		public Criteria andMainbrandNotLike(String value) {
			addCriterion("f_mainbrand not like", value, "mainbrand");
			return (Criteria) this;
		}

		public Criteria andMainbrandIn(List<String> values) {
			addCriterion("f_mainbrand in", values, "mainbrand");
			return (Criteria) this;
		}

		public Criteria andMainbrandNotIn(List<String> values) {
			addCriterion("f_mainbrand not in", values, "mainbrand");
			return (Criteria) this;
		}

		public Criteria andMainbrandBetween(String value1, String value2) {
			addCriterion("f_mainbrand between", value1, value2, "mainbrand");
			return (Criteria) this;
		}

		public Criteria andMainbrandNotBetween(String value1, String value2) {
			addCriterion("f_mainbrand not between", value1, value2, "mainbrand");
			return (Criteria) this;
		}

		public Criteria andAreaIsNull() {
			addCriterion("f_area is null");
			return (Criteria) this;
		}

		public Criteria andAreaIsNotNull() {
			addCriterion("f_area is not null");
			return (Criteria) this;
		}

		public Criteria andAreaEqualTo(Short value) {
			addCriterion("f_area =", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotEqualTo(Short value) {
			addCriterion("f_area <>", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaGreaterThan(Short value) {
			addCriterion("f_area >", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaGreaterThanOrEqualTo(Short value) {
			addCriterion("f_area >=", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaLessThan(Short value) {
			addCriterion("f_area <", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaLessThanOrEqualTo(Short value) {
			addCriterion("f_area <=", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaIn(List<Short> values) {
			addCriterion("f_area in", values, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotIn(List<Short> values) {
			addCriterion("f_area not in", values, "area");
			return (Criteria) this;
		}

		public Criteria andAreaBetween(Short value1, Short value2) {
			addCriterion("f_area between", value1, value2, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotBetween(Short value1, Short value2) {
			addCriterion("f_area not between", value1, value2, "area");
			return (Criteria) this;
		}

		public Criteria andSelltelIsNull() {
			addCriterion("f_selltel is null");
			return (Criteria) this;
		}

		public Criteria andSelltelIsNotNull() {
			addCriterion("f_selltel is not null");
			return (Criteria) this;
		}

		public Criteria andSelltelEqualTo(String value) {
			addCriterion("f_selltel =", value, "selltel");
			return (Criteria) this;
		}

		public Criteria andSelltelNotEqualTo(String value) {
			addCriterion("f_selltel <>", value, "selltel");
			return (Criteria) this;
		}

		public Criteria andSelltelGreaterThan(String value) {
			addCriterion("f_selltel >", value, "selltel");
			return (Criteria) this;
		}

		public Criteria andSelltelGreaterThanOrEqualTo(String value) {
			addCriterion("f_selltel >=", value, "selltel");
			return (Criteria) this;
		}

		public Criteria andSelltelLessThan(String value) {
			addCriterion("f_selltel <", value, "selltel");
			return (Criteria) this;
		}

		public Criteria andSelltelLessThanOrEqualTo(String value) {
			addCriterion("f_selltel <=", value, "selltel");
			return (Criteria) this;
		}

		public Criteria andSelltelLike(String value) {
			addCriterion("f_selltel like", value, "selltel");
			return (Criteria) this;
		}

		public Criteria andSelltelNotLike(String value) {
			addCriterion("f_selltel not like", value, "selltel");
			return (Criteria) this;
		}

		public Criteria andSelltelIn(List<String> values) {
			addCriterion("f_selltel in", values, "selltel");
			return (Criteria) this;
		}

		public Criteria andSelltelNotIn(List<String> values) {
			addCriterion("f_selltel not in", values, "selltel");
			return (Criteria) this;
		}

		public Criteria andSelltelBetween(String value1, String value2) {
			addCriterion("f_selltel between", value1, value2, "selltel");
			return (Criteria) this;
		}

		public Criteria andSelltelNotBetween(String value1, String value2) {
			addCriterion("f_selltel not between", value1, value2, "selltel");
			return (Criteria) this;
		}

		public Criteria andWebaddrIsNull() {
			addCriterion("f_webaddr is null");
			return (Criteria) this;
		}

		public Criteria andWebaddrIsNotNull() {
			addCriterion("f_webaddr is not null");
			return (Criteria) this;
		}

		public Criteria andWebaddrEqualTo(String value) {
			addCriterion("f_webaddr =", value, "webaddr");
			return (Criteria) this;
		}

		public Criteria andWebaddrNotEqualTo(String value) {
			addCriterion("f_webaddr <>", value, "webaddr");
			return (Criteria) this;
		}

		public Criteria andWebaddrGreaterThan(String value) {
			addCriterion("f_webaddr >", value, "webaddr");
			return (Criteria) this;
		}

		public Criteria andWebaddrGreaterThanOrEqualTo(String value) {
			addCriterion("f_webaddr >=", value, "webaddr");
			return (Criteria) this;
		}

		public Criteria andWebaddrLessThan(String value) {
			addCriterion("f_webaddr <", value, "webaddr");
			return (Criteria) this;
		}

		public Criteria andWebaddrLessThanOrEqualTo(String value) {
			addCriterion("f_webaddr <=", value, "webaddr");
			return (Criteria) this;
		}

		public Criteria andWebaddrLike(String value) {
			addCriterion("f_webaddr like", value, "webaddr");
			return (Criteria) this;
		}

		public Criteria andWebaddrNotLike(String value) {
			addCriterion("f_webaddr not like", value, "webaddr");
			return (Criteria) this;
		}

		public Criteria andWebaddrIn(List<String> values) {
			addCriterion("f_webaddr in", values, "webaddr");
			return (Criteria) this;
		}

		public Criteria andWebaddrNotIn(List<String> values) {
			addCriterion("f_webaddr not in", values, "webaddr");
			return (Criteria) this;
		}

		public Criteria andWebaddrBetween(String value1, String value2) {
			addCriterion("f_webaddr between", value1, value2, "webaddr");
			return (Criteria) this;
		}

		public Criteria andWebaddrNotBetween(String value1, String value2) {
			addCriterion("f_webaddr not between", value1, value2, "webaddr");
			return (Criteria) this;
		}

		public Criteria andLevelIsNull() {
			addCriterion("f_level is null");
			return (Criteria) this;
		}

		public Criteria andLevelIsNotNull() {
			addCriterion("f_level is not null");
			return (Criteria) this;
		}

		public Criteria andLevelEqualTo(String value) {
			addCriterion("f_level =", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotEqualTo(String value) {
			addCriterion("f_level <>", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThan(String value) {
			addCriterion("f_level >", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThanOrEqualTo(String value) {
			addCriterion("f_level >=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThan(String value) {
			addCriterion("f_level <", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThanOrEqualTo(String value) {
			addCriterion("f_level <=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLike(String value) {
			addCriterion("f_level like", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotLike(String value) {
			addCriterion("f_level not like", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelIn(List<String> values) {
			addCriterion("f_level in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotIn(List<String> values) {
			addCriterion("f_level not in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelBetween(String value1, String value2) {
			addCriterion("f_level between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotBetween(String value1, String value2) {
			addCriterion("f_level not between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andMainVehicleIsNull() {
			addCriterion("f_main_vehicle is null");
			return (Criteria) this;
		}

		public Criteria andMainVehicleIsNotNull() {
			addCriterion("f_main_vehicle is not null");
			return (Criteria) this;
		}

		public Criteria andMainVehicleEqualTo(String value) {
			addCriterion("f_main_vehicle =", value, "mainVehicle");
			return (Criteria) this;
		}

		public Criteria andMainVehicleNotEqualTo(String value) {
			addCriterion("f_main_vehicle <>", value, "mainVehicle");
			return (Criteria) this;
		}

		public Criteria andMainVehicleGreaterThan(String value) {
			addCriterion("f_main_vehicle >", value, "mainVehicle");
			return (Criteria) this;
		}

		public Criteria andMainVehicleGreaterThanOrEqualTo(String value) {
			addCriterion("f_main_vehicle >=", value, "mainVehicle");
			return (Criteria) this;
		}

		public Criteria andMainVehicleLessThan(String value) {
			addCriterion("f_main_vehicle <", value, "mainVehicle");
			return (Criteria) this;
		}

		public Criteria andMainVehicleLessThanOrEqualTo(String value) {
			addCriterion("f_main_vehicle <=", value, "mainVehicle");
			return (Criteria) this;
		}

		public Criteria andMainVehicleLike(String value) {
			addCriterion("f_main_vehicle like", value, "mainVehicle");
			return (Criteria) this;
		}

		public Criteria andMainVehicleNotLike(String value) {
			addCriterion("f_main_vehicle not like", value, "mainVehicle");
			return (Criteria) this;
		}

		public Criteria andMainVehicleIn(List<String> values) {
			addCriterion("f_main_vehicle in", values, "mainVehicle");
			return (Criteria) this;
		}

		public Criteria andMainVehicleNotIn(List<String> values) {
			addCriterion("f_main_vehicle not in", values, "mainVehicle");
			return (Criteria) this;
		}

		public Criteria andMainVehicleBetween(String value1, String value2) {
			addCriterion("f_main_vehicle between", value1, value2, "mainVehicle");
			return (Criteria) this;
		}

		public Criteria andMainVehicleNotBetween(String value1, String value2) {
			addCriterion("f_main_vehicle not between", value1, value2, "mainVehicle");
			return (Criteria) this;
		}

		public Criteria andStidIsNull() {
			addCriterion("f_stid is null");
			return (Criteria) this;
		}

		public Criteria andStidIsNotNull() {
			addCriterion("f_stid is not null");
			return (Criteria) this;
		}

		public Criteria andStidEqualTo(String value) {
			addCriterion("f_stid =", value, "stid");
			return (Criteria) this;
		}

		public Criteria andStidNotEqualTo(String value) {
			addCriterion("f_stid <>", value, "stid");
			return (Criteria) this;
		}

		public Criteria andStidGreaterThan(String value) {
			addCriterion("f_stid >", value, "stid");
			return (Criteria) this;
		}

		public Criteria andStidGreaterThanOrEqualTo(String value) {
			addCriterion("f_stid >=", value, "stid");
			return (Criteria) this;
		}

		public Criteria andStidLessThan(String value) {
			addCriterion("f_stid <", value, "stid");
			return (Criteria) this;
		}

		public Criteria andStidLessThanOrEqualTo(String value) {
			addCriterion("f_stid <=", value, "stid");
			return (Criteria) this;
		}

		public Criteria andStidLike(String value) {
			addCriterion("f_stid like", value, "stid");
			return (Criteria) this;
		}

		public Criteria andStidNotLike(String value) {
			addCriterion("f_stid not like", value, "stid");
			return (Criteria) this;
		}

		public Criteria andStidIn(List<String> values) {
			addCriterion("f_stid in", values, "stid");
			return (Criteria) this;
		}

		public Criteria andStidNotIn(List<String> values) {
			addCriterion("f_stid not in", values, "stid");
			return (Criteria) this;
		}

		public Criteria andStidBetween(String value1, String value2) {
			addCriterion("f_stid between", value1, value2, "stid");
			return (Criteria) this;
		}

		public Criteria andStidNotBetween(String value1, String value2) {
			addCriterion("f_stid not between", value1, value2, "stid");
			return (Criteria) this;
		}

		public Criteria andContactIsNull() {
			addCriterion("f_contact is null");
			return (Criteria) this;
		}

		public Criteria andContactIsNotNull() {
			addCriterion("f_contact is not null");
			return (Criteria) this;
		}

		public Criteria andContactEqualTo(String value) {
			addCriterion("f_contact =", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactNotEqualTo(String value) {
			addCriterion("f_contact <>", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactGreaterThan(String value) {
			addCriterion("f_contact >", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactGreaterThanOrEqualTo(String value) {
			addCriterion("f_contact >=", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactLessThan(String value) {
			addCriterion("f_contact <", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactLessThanOrEqualTo(String value) {
			addCriterion("f_contact <=", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactLike(String value) {
			addCriterion("f_contact like", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactNotLike(String value) {
			addCriterion("f_contact not like", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactIn(List<String> values) {
			addCriterion("f_contact in", values, "contact");
			return (Criteria) this;
		}

		public Criteria andContactNotIn(List<String> values) {
			addCriterion("f_contact not in", values, "contact");
			return (Criteria) this;
		}

		public Criteria andContactBetween(String value1, String value2) {
			addCriterion("f_contact between", value1, value2, "contact");
			return (Criteria) this;
		}

		public Criteria andContactNotBetween(String value1, String value2) {
			addCriterion("f_contact not between", value1, value2, "contact");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_um_newcar
	 * @mbggenerated  Thu Feb 25 11:29:12 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_um_newcar
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 23 16:34:40 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}