package com.etong.pt.data.sysbanner;

import java.io.Serializable;

public class SysBanner implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_banner.f_bnid
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    private Long bnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_banner.f_url
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_banner.f_aid
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_banner.f_order
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_banner.f_initdate
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    private Integer initdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_banner.f_editorid
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    private Long editorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_banner.f_editor
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_banner.f_stid
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    private String stid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_banner.f_image
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_banner.f_desc
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_banner.f_bnid
     *
     * @return the value of t_sys_banner.f_bnid
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public Long getBnid() {
        return bnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_banner.f_bnid
     *
     * @param bnid the value for t_sys_banner.f_bnid
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public void setBnid(Long bnid) {
        this.bnid = bnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_banner.f_url
     *
     * @return the value of t_sys_banner.f_url
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_banner.f_url
     *
     * @param url the value for t_sys_banner.f_url
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_banner.f_aid
     *
     * @return the value of t_sys_banner.f_aid
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_banner.f_aid
     *
     * @param aid the value for t_sys_banner.f_aid
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_banner.f_order
     *
     * @return the value of t_sys_banner.f_order
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_banner.f_order
     *
     * @param order the value for t_sys_banner.f_order
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_banner.f_initdate
     *
     * @return the value of t_sys_banner.f_initdate
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public Integer getInitdate() {
        return initdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_banner.f_initdate
     *
     * @param initdate the value for t_sys_banner.f_initdate
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public void setInitdate(Integer initdate) {
        this.initdate = initdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_banner.f_editorid
     *
     * @return the value of t_sys_banner.f_editorid
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public Long getEditorid() {
        return editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_banner.f_editorid
     *
     * @param editorid the value for t_sys_banner.f_editorid
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public void setEditorid(Long editorid) {
        this.editorid = editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_banner.f_editor
     *
     * @return the value of t_sys_banner.f_editor
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_banner.f_editor
     *
     * @param editor the value for t_sys_banner.f_editor
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public void setEditor(String editor) {
        this.editor = editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_banner.f_stid
     *
     * @return the value of t_sys_banner.f_stid
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public String getStid() {
        return stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_banner.f_stid
     *
     * @param stid the value for t_sys_banner.f_stid
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public void setStid(String stid) {
        this.stid = stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_banner.f_image
     *
     * @return the value of t_sys_banner.f_image
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_banner.f_image
     *
     * @param image the value for t_sys_banner.f_image
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_banner.f_desc
     *
     * @return the value of t_sys_banner.f_desc
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_banner.f_desc
     *
     * @param desc the value for t_sys_banner.f_desc
     *
     * @mbggenerated Tue Dec 01 09:44:32 CST 2015
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}