package com.etong.pt.data.appvehicle;

import java.io.Serializable;

public class AppVehicle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_appvehicle.f_dvid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    private Long dvid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_appvehicle.f_stid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    private String stid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_appvehicle.f_carbrand
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    private String carbrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_appvehicle.f_carset
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    private String carset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_appvehicle.f_cartype
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    private String cartype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_appvehicle.f_carbrandid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    private Integer carbrandid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_appvehicle.f_carsetid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    private Integer carsetid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_appvehicle.f_cartypeid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    private Integer cartypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_appvehicle.f_status
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_appvehicle.f_level
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_appvehicle.f_desc
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_appvehicle.f_dvid
     *
     * @return the value of t_bd_appvehicle.f_dvid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public Long getDvid() {
        return dvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_appvehicle.f_dvid
     *
     * @param dvid the value for t_bd_appvehicle.f_dvid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void setDvid(Long dvid) {
        this.dvid = dvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_appvehicle.f_stid
     *
     * @return the value of t_bd_appvehicle.f_stid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public String getStid() {
        return stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_appvehicle.f_stid
     *
     * @param stid the value for t_bd_appvehicle.f_stid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void setStid(String stid) {
        this.stid = stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_appvehicle.f_carbrand
     *
     * @return the value of t_bd_appvehicle.f_carbrand
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public String getCarbrand() {
        return carbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_appvehicle.f_carbrand
     *
     * @param carbrand the value for t_bd_appvehicle.f_carbrand
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void setCarbrand(String carbrand) {
        this.carbrand = carbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_appvehicle.f_carset
     *
     * @return the value of t_bd_appvehicle.f_carset
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public String getCarset() {
        return carset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_appvehicle.f_carset
     *
     * @param carset the value for t_bd_appvehicle.f_carset
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void setCarset(String carset) {
        this.carset = carset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_appvehicle.f_cartype
     *
     * @return the value of t_bd_appvehicle.f_cartype
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public String getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_appvehicle.f_cartype
     *
     * @param cartype the value for t_bd_appvehicle.f_cartype
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void setCartype(String cartype) {
        this.cartype = cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_appvehicle.f_carbrandid
     *
     * @return the value of t_bd_appvehicle.f_carbrandid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public Integer getCarbrandid() {
        return carbrandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_appvehicle.f_carbrandid
     *
     * @param carbrandid the value for t_bd_appvehicle.f_carbrandid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void setCarbrandid(Integer carbrandid) {
        this.carbrandid = carbrandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_appvehicle.f_carsetid
     *
     * @return the value of t_bd_appvehicle.f_carsetid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public Integer getCarsetid() {
        return carsetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_appvehicle.f_carsetid
     *
     * @param carsetid the value for t_bd_appvehicle.f_carsetid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void setCarsetid(Integer carsetid) {
        this.carsetid = carsetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_appvehicle.f_cartypeid
     *
     * @return the value of t_bd_appvehicle.f_cartypeid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public Integer getCartypeid() {
        return cartypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_appvehicle.f_cartypeid
     *
     * @param cartypeid the value for t_bd_appvehicle.f_cartypeid
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void setCartypeid(Integer cartypeid) {
        this.cartypeid = cartypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_appvehicle.f_status
     *
     * @return the value of t_bd_appvehicle.f_status
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_appvehicle.f_status
     *
     * @param status the value for t_bd_appvehicle.f_status
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_appvehicle.f_level
     *
     * @return the value of t_bd_appvehicle.f_level
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_appvehicle.f_level
     *
     * @param level the value for t_bd_appvehicle.f_level
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_appvehicle.f_desc
     *
     * @return the value of t_bd_appvehicle.f_desc
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_appvehicle.f_desc
     *
     * @param desc the value for t_bd_appvehicle.f_desc
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}