package com.etong.pt.data.appvehicle;

import java.util.ArrayList;
import java.util.List;

public class AppVehicleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public AppVehicleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDvidIsNull() {
            addCriterion("f_dvid is null");
            return (Criteria) this;
        }

        public Criteria andDvidIsNotNull() {
            addCriterion("f_dvid is not null");
            return (Criteria) this;
        }

        public Criteria andDvidEqualTo(Long value) {
            addCriterion("f_dvid =", value, "dvid");
            return (Criteria) this;
        }

        public Criteria andDvidNotEqualTo(Long value) {
            addCriterion("f_dvid <>", value, "dvid");
            return (Criteria) this;
        }

        public Criteria andDvidGreaterThan(Long value) {
            addCriterion("f_dvid >", value, "dvid");
            return (Criteria) this;
        }

        public Criteria andDvidGreaterThanOrEqualTo(Long value) {
            addCriterion("f_dvid >=", value, "dvid");
            return (Criteria) this;
        }

        public Criteria andDvidLessThan(Long value) {
            addCriterion("f_dvid <", value, "dvid");
            return (Criteria) this;
        }

        public Criteria andDvidLessThanOrEqualTo(Long value) {
            addCriterion("f_dvid <=", value, "dvid");
            return (Criteria) this;
        }

        public Criteria andDvidIn(List<Long> values) {
            addCriterion("f_dvid in", values, "dvid");
            return (Criteria) this;
        }

        public Criteria andDvidNotIn(List<Long> values) {
            addCriterion("f_dvid not in", values, "dvid");
            return (Criteria) this;
        }

        public Criteria andDvidBetween(Long value1, Long value2) {
            addCriterion("f_dvid between", value1, value2, "dvid");
            return (Criteria) this;
        }

        public Criteria andDvidNotBetween(Long value1, Long value2) {
            addCriterion("f_dvid not between", value1, value2, "dvid");
            return (Criteria) this;
        }

        public Criteria andStidIsNull() {
            addCriterion("f_stid is null");
            return (Criteria) this;
        }

        public Criteria andStidIsNotNull() {
            addCriterion("f_stid is not null");
            return (Criteria) this;
        }

        public Criteria andStidEqualTo(String value) {
            addCriterion("f_stid =", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidNotEqualTo(String value) {
            addCriterion("f_stid <>", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidGreaterThan(String value) {
            addCriterion("f_stid >", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidGreaterThanOrEqualTo(String value) {
            addCriterion("f_stid >=", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidLessThan(String value) {
            addCriterion("f_stid <", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidLessThanOrEqualTo(String value) {
            addCriterion("f_stid <=", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidLike(String value) {
            addCriterion("f_stid like", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidNotLike(String value) {
            addCriterion("f_stid not like", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidIn(List<String> values) {
            addCriterion("f_stid in", values, "stid");
            return (Criteria) this;
        }

        public Criteria andStidNotIn(List<String> values) {
            addCriterion("f_stid not in", values, "stid");
            return (Criteria) this;
        }

        public Criteria andStidBetween(String value1, String value2) {
            addCriterion("f_stid between", value1, value2, "stid");
            return (Criteria) this;
        }

        public Criteria andStidNotBetween(String value1, String value2) {
            addCriterion("f_stid not between", value1, value2, "stid");
            return (Criteria) this;
        }

        public Criteria andCarbrandIsNull() {
            addCriterion("f_carbrand is null");
            return (Criteria) this;
        }

        public Criteria andCarbrandIsNotNull() {
            addCriterion("f_carbrand is not null");
            return (Criteria) this;
        }

        public Criteria andCarbrandEqualTo(String value) {
            addCriterion("f_carbrand =", value, "carbrand");
            return (Criteria) this;
        }

        public Criteria andCarbrandNotEqualTo(String value) {
            addCriterion("f_carbrand <>", value, "carbrand");
            return (Criteria) this;
        }

        public Criteria andCarbrandGreaterThan(String value) {
            addCriterion("f_carbrand >", value, "carbrand");
            return (Criteria) this;
        }

        public Criteria andCarbrandGreaterThanOrEqualTo(String value) {
            addCriterion("f_carbrand >=", value, "carbrand");
            return (Criteria) this;
        }

        public Criteria andCarbrandLessThan(String value) {
            addCriterion("f_carbrand <", value, "carbrand");
            return (Criteria) this;
        }

        public Criteria andCarbrandLessThanOrEqualTo(String value) {
            addCriterion("f_carbrand <=", value, "carbrand");
            return (Criteria) this;
        }

        public Criteria andCarbrandLike(String value) {
            addCriterion("f_carbrand like", value, "carbrand");
            return (Criteria) this;
        }

        public Criteria andCarbrandNotLike(String value) {
            addCriterion("f_carbrand not like", value, "carbrand");
            return (Criteria) this;
        }

        public Criteria andCarbrandIn(List<String> values) {
            addCriterion("f_carbrand in", values, "carbrand");
            return (Criteria) this;
        }

        public Criteria andCarbrandNotIn(List<String> values) {
            addCriterion("f_carbrand not in", values, "carbrand");
            return (Criteria) this;
        }

        public Criteria andCarbrandBetween(String value1, String value2) {
            addCriterion("f_carbrand between", value1, value2, "carbrand");
            return (Criteria) this;
        }

        public Criteria andCarbrandNotBetween(String value1, String value2) {
            addCriterion("f_carbrand not between", value1, value2, "carbrand");
            return (Criteria) this;
        }

        public Criteria andCarsetIsNull() {
            addCriterion("f_carset is null");
            return (Criteria) this;
        }

        public Criteria andCarsetIsNotNull() {
            addCriterion("f_carset is not null");
            return (Criteria) this;
        }

        public Criteria andCarsetEqualTo(String value) {
            addCriterion("f_carset =", value, "carset");
            return (Criteria) this;
        }

        public Criteria andCarsetNotEqualTo(String value) {
            addCriterion("f_carset <>", value, "carset");
            return (Criteria) this;
        }

        public Criteria andCarsetGreaterThan(String value) {
            addCriterion("f_carset >", value, "carset");
            return (Criteria) this;
        }

        public Criteria andCarsetGreaterThanOrEqualTo(String value) {
            addCriterion("f_carset >=", value, "carset");
            return (Criteria) this;
        }

        public Criteria andCarsetLessThan(String value) {
            addCriterion("f_carset <", value, "carset");
            return (Criteria) this;
        }

        public Criteria andCarsetLessThanOrEqualTo(String value) {
            addCriterion("f_carset <=", value, "carset");
            return (Criteria) this;
        }

        public Criteria andCarsetLike(String value) {
            addCriterion("f_carset like", value, "carset");
            return (Criteria) this;
        }

        public Criteria andCarsetNotLike(String value) {
            addCriterion("f_carset not like", value, "carset");
            return (Criteria) this;
        }

        public Criteria andCarsetIn(List<String> values) {
            addCriterion("f_carset in", values, "carset");
            return (Criteria) this;
        }

        public Criteria andCarsetNotIn(List<String> values) {
            addCriterion("f_carset not in", values, "carset");
            return (Criteria) this;
        }

        public Criteria andCarsetBetween(String value1, String value2) {
            addCriterion("f_carset between", value1, value2, "carset");
            return (Criteria) this;
        }

        public Criteria andCarsetNotBetween(String value1, String value2) {
            addCriterion("f_carset not between", value1, value2, "carset");
            return (Criteria) this;
        }

        public Criteria andCartypeIsNull() {
            addCriterion("f_cartype is null");
            return (Criteria) this;
        }

        public Criteria andCartypeIsNotNull() {
            addCriterion("f_cartype is not null");
            return (Criteria) this;
        }

        public Criteria andCartypeEqualTo(String value) {
            addCriterion("f_cartype =", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotEqualTo(String value) {
            addCriterion("f_cartype <>", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeGreaterThan(String value) {
            addCriterion("f_cartype >", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeGreaterThanOrEqualTo(String value) {
            addCriterion("f_cartype >=", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeLessThan(String value) {
            addCriterion("f_cartype <", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeLessThanOrEqualTo(String value) {
            addCriterion("f_cartype <=", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeLike(String value) {
            addCriterion("f_cartype like", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotLike(String value) {
            addCriterion("f_cartype not like", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeIn(List<String> values) {
            addCriterion("f_cartype in", values, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotIn(List<String> values) {
            addCriterion("f_cartype not in", values, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeBetween(String value1, String value2) {
            addCriterion("f_cartype between", value1, value2, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotBetween(String value1, String value2) {
            addCriterion("f_cartype not between", value1, value2, "cartype");
            return (Criteria) this;
        }

        public Criteria andCarbrandidIsNull() {
            addCriterion("f_carbrandid is null");
            return (Criteria) this;
        }

        public Criteria andCarbrandidIsNotNull() {
            addCriterion("f_carbrandid is not null");
            return (Criteria) this;
        }

        public Criteria andCarbrandidEqualTo(Integer value) {
            addCriterion("f_carbrandid =", value, "carbrandid");
            return (Criteria) this;
        }

        public Criteria andCarbrandidNotEqualTo(Integer value) {
            addCriterion("f_carbrandid <>", value, "carbrandid");
            return (Criteria) this;
        }

        public Criteria andCarbrandidGreaterThan(Integer value) {
            addCriterion("f_carbrandid >", value, "carbrandid");
            return (Criteria) this;
        }

        public Criteria andCarbrandidGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_carbrandid >=", value, "carbrandid");
            return (Criteria) this;
        }

        public Criteria andCarbrandidLessThan(Integer value) {
            addCriterion("f_carbrandid <", value, "carbrandid");
            return (Criteria) this;
        }

        public Criteria andCarbrandidLessThanOrEqualTo(Integer value) {
            addCriterion("f_carbrandid <=", value, "carbrandid");
            return (Criteria) this;
        }

        public Criteria andCarbrandidIn(List<Integer> values) {
            addCriterion("f_carbrandid in", values, "carbrandid");
            return (Criteria) this;
        }

        public Criteria andCarbrandidNotIn(List<Integer> values) {
            addCriterion("f_carbrandid not in", values, "carbrandid");
            return (Criteria) this;
        }

        public Criteria andCarbrandidBetween(Integer value1, Integer value2) {
            addCriterion("f_carbrandid between", value1, value2, "carbrandid");
            return (Criteria) this;
        }

        public Criteria andCarbrandidNotBetween(Integer value1, Integer value2) {
            addCriterion("f_carbrandid not between", value1, value2, "carbrandid");
            return (Criteria) this;
        }

        public Criteria andCarsetidIsNull() {
            addCriterion("f_carsetid is null");
            return (Criteria) this;
        }

        public Criteria andCarsetidIsNotNull() {
            addCriterion("f_carsetid is not null");
            return (Criteria) this;
        }

        public Criteria andCarsetidEqualTo(Integer value) {
            addCriterion("f_carsetid =", value, "carsetid");
            return (Criteria) this;
        }

        public Criteria andCarsetidNotEqualTo(Integer value) {
            addCriterion("f_carsetid <>", value, "carsetid");
            return (Criteria) this;
        }

        public Criteria andCarsetidGreaterThan(Integer value) {
            addCriterion("f_carsetid >", value, "carsetid");
            return (Criteria) this;
        }

        public Criteria andCarsetidGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_carsetid >=", value, "carsetid");
            return (Criteria) this;
        }

        public Criteria andCarsetidLessThan(Integer value) {
            addCriterion("f_carsetid <", value, "carsetid");
            return (Criteria) this;
        }

        public Criteria andCarsetidLessThanOrEqualTo(Integer value) {
            addCriterion("f_carsetid <=", value, "carsetid");
            return (Criteria) this;
        }

        public Criteria andCarsetidIn(List<Integer> values) {
            addCriterion("f_carsetid in", values, "carsetid");
            return (Criteria) this;
        }

        public Criteria andCarsetidNotIn(List<Integer> values) {
            addCriterion("f_carsetid not in", values, "carsetid");
            return (Criteria) this;
        }

        public Criteria andCarsetidBetween(Integer value1, Integer value2) {
            addCriterion("f_carsetid between", value1, value2, "carsetid");
            return (Criteria) this;
        }

        public Criteria andCarsetidNotBetween(Integer value1, Integer value2) {
            addCriterion("f_carsetid not between", value1, value2, "carsetid");
            return (Criteria) this;
        }

        public Criteria andCartypeidIsNull() {
            addCriterion("f_cartypeid is null");
            return (Criteria) this;
        }

        public Criteria andCartypeidIsNotNull() {
            addCriterion("f_cartypeid is not null");
            return (Criteria) this;
        }

        public Criteria andCartypeidEqualTo(Integer value) {
            addCriterion("f_cartypeid =", value, "cartypeid");
            return (Criteria) this;
        }

        public Criteria andCartypeidNotEqualTo(Integer value) {
            addCriterion("f_cartypeid <>", value, "cartypeid");
            return (Criteria) this;
        }

        public Criteria andCartypeidGreaterThan(Integer value) {
            addCriterion("f_cartypeid >", value, "cartypeid");
            return (Criteria) this;
        }

        public Criteria andCartypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_cartypeid >=", value, "cartypeid");
            return (Criteria) this;
        }

        public Criteria andCartypeidLessThan(Integer value) {
            addCriterion("f_cartypeid <", value, "cartypeid");
            return (Criteria) this;
        }

        public Criteria andCartypeidLessThanOrEqualTo(Integer value) {
            addCriterion("f_cartypeid <=", value, "cartypeid");
            return (Criteria) this;
        }

        public Criteria andCartypeidIn(List<Integer> values) {
            addCriterion("f_cartypeid in", values, "cartypeid");
            return (Criteria) this;
        }

        public Criteria andCartypeidNotIn(List<Integer> values) {
            addCriterion("f_cartypeid not in", values, "cartypeid");
            return (Criteria) this;
        }

        public Criteria andCartypeidBetween(Integer value1, Integer value2) {
            addCriterion("f_cartypeid between", value1, value2, "cartypeid");
            return (Criteria) this;
        }

        public Criteria andCartypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("f_cartypeid not between", value1, value2, "cartypeid");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("f_status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("f_status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("f_status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("f_status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("f_status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("f_status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("f_status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("f_status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("f_status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("f_status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("f_status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("f_status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("f_level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("f_level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("f_level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("f_level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("f_level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("f_level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("f_level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("f_level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("f_level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("f_level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("f_level not between", value1, value2, "level");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 08 11:09:41 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bd_appvehicle
     *
     * @mbggenerated Tue Dec 08 11:09:41 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}