package com.etong.pt.data.hotvehicle;

import java.io.Serializable;

public class HotVehicle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_hotvehicle.f_hvid
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    private Integer f_hvid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_hotvehicle.f_vid
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    private Integer f_vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_hotvehicle.f_order
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    private Integer f_order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_hotvehicle.f_type
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    private Integer f_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_hotvehicle.f_stid
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    private String f_stid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_hotvehicle.f_hvid
     *
     * @return the value of t_bd_hotvehicle.f_hvid
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    public Integer getF_hvid() {
        return f_hvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_hotvehicle.f_hvid
     *
     * @param f_hvid the value for t_bd_hotvehicle.f_hvid
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    public void setF_hvid(Integer f_hvid) {
        this.f_hvid = f_hvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_hotvehicle.f_vid
     *
     * @return the value of t_bd_hotvehicle.f_vid
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    public Integer getF_vid() {
        return f_vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_hotvehicle.f_vid
     *
     * @param f_vid the value for t_bd_hotvehicle.f_vid
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    public void setF_vid(Integer f_vid) {
        this.f_vid = f_vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_hotvehicle.f_order
     *
     * @return the value of t_bd_hotvehicle.f_order
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    public Integer getF_order() {
        return f_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_hotvehicle.f_order
     *
     * @param f_order the value for t_bd_hotvehicle.f_order
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    public void setF_order(Integer f_order) {
        this.f_order = f_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_hotvehicle.f_type
     *
     * @return the value of t_bd_hotvehicle.f_type
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    public Integer getF_type() {
        return f_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_hotvehicle.f_type
     *
     * @param f_type the value for t_bd_hotvehicle.f_type
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    public void setF_type(Integer f_type) {
        this.f_type = f_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_hotvehicle.f_stid
     *
     * @return the value of t_bd_hotvehicle.f_stid
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    public String getF_stid() {
        return f_stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_hotvehicle.f_stid
     *
     * @param f_stid the value for t_bd_hotvehicle.f_stid
     *
     * @mbggenerated Wed Oct 21 09:42:00 CST 2015
     */
    public void setF_stid(String f_stid) {
        this.f_stid = f_stid == null ? null : f_stid.trim();
    }
}